// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK: #[[$ATTR_0:.+]] = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
// CHECK: #[[$ATTR_1:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_2:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
// CHECK: #[[$ATTR_3:.+]] = #ttg.shared_memory
// CHECK: #[[$ATTR_4:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
// RUN: triton-opt %s -split-input-file -allow-unregistered-dialect --nvws-insert-semas -cse | FileCheck %s

// M2 PIN (nested-loop hold-rule extension, plan v3).
//
// A WS-tagged OUTER loop wrapping a non-WS INNER loop with ONE inner-confined
// ping-pong buffer (the persistent-FA qk shape, design v3 §8): tc_gen5_mma
// (partition 1) writes the tmem accumulator, tmem_load (partition 0) reads it,
// BOTH confined to the inner loop; nothing touches the buffer at the outer
// level.
//
// This pins the enabled native shape: no root entry acquire, no added carrier
// iter_args on either loop, and the writer acquire moved to the first toucher.

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func @nested_ws_inner_loop(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32) {
// CHECK:           %[[VAL_3:.*]] = ub.poison : !ttg.async.token
// CHECK:           %[[VAL_4:.*]] = arith.constant true
// CHECK:           %[[VAL_5:.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_6:.*]] = nvws.semaphore.create %[[VAL_5]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_7:.*]] = nvws.semaphore.create %[[VAL_5]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_8:.*]] = scf.for %[[VAL_9:.*]] = %[[VAL_0]] to %[[VAL_1]] step %[[VAL_2]] iter_args(%[[VAL_10:.*]] = %[[VAL_3]]) -> (!ttg.async.token)  : i32 {
// CHECK:             %[[VAL_11:.*]] = scf.for %[[VAL_12:.*]] = %[[VAL_0]] to %[[VAL_1]] step %[[VAL_2]] iter_args(%[[VAL_13:.*]] = %[[VAL_10]]) -> (!ttg.async.token)  : i32 {
// CHECK:               %[[VAL_14:.*]] = "loadA"(%[[VAL_12]]) {ttg.partition = array<i32: 1>} : (i32) -> !ttg.memdesc<128x64xf16, #[[$ATTR_1]], #[[$ATTR_3]]>
// CHECK:               %[[VAL_15:.*]] = "loadB"(%[[VAL_12]]) {ttg.partition = array<i32: 1>} : (i32) -> !ttg.memdesc<64x128xf16, #[[$ATTR_2]], #[[$ATTR_3]]>
// CHECK:               %[[VAL_16:.*]] = nvws.semaphore.acquire %[[VAL_6]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_17:.*]] = nvws.semaphore.buffer %[[VAL_6]], %[[VAL_16]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_18:.*]] = ttng.tc_gen5_mma %[[VAL_14]], %[[VAL_15]], %[[VAL_17]][], %[[VAL_4]], %[[VAL_4]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_1]], #[[$ATTR_3]]>, !ttg.memdesc<64x128xf16, #[[$ATTR_2]], #[[$ATTR_3]]>, !ttg.memdesc<128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_7]], %[[VAL_16]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_19:.*]] = nvws.semaphore.acquire %[[VAL_7]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_20:.*]] = nvws.semaphore.buffer %[[VAL_7]], %[[VAL_19]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_21:.*]], %[[VAL_22:.*]] = ttng.tmem_load %[[VAL_20]][] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_0]]>
// CHECK:               nvws.semaphore.release %[[VAL_6]], %[[VAL_19]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_4]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               "use"(%[[VAL_21]]) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #[[$ATTR_0]]>) -> ()
// CHECK:               scf.yield {ttg.partition = array<i32: 0, 1>} %[[VAL_3]] : !ttg.async.token
// CHECK:             } {ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 0>]}
// CHECK:             scf.yield {ttg.partition = array<i32: 0, 1>} %[[VAL_11]] : !ttg.async.token
// CHECK:           } {tt.warp_specialize, ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 0>], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           tt.return
// CHECK:         }
  tt.func @nested_ws_inner_loop(%lb: i32, %ub: i32, %step: i32) {
    %true = arith.constant true
    %res, %tok = ttng.tmem_alloc : () -> (!ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>, !ttg.async.token)
    %o = scf.for %iv0 = %lb to %ub step %step iter_args(%t0 = %tok) -> (!ttg.async.token) : i32 {
      %i = scf.for %iv = %lb to %ub step %step iter_args(%t1 = %t0) -> (!ttg.async.token) : i32 {
        %sA = "loadA"(%iv) {ttg.partition = array<i32: 1>} : (i32) -> !ttg.memdesc<128x64xf16, #shared, #smem>
        %sB = "loadB"(%iv) {ttg.partition = array<i32: 1>} : (i32) -> !ttg.memdesc<64x128xf16, #shared1, #smem>
        %mma = ttng.tc_gen5_mma %sA, %sB, %res[%t1], %true, %true {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.memdesc<64x128xf16, #shared1, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
        %val, %t2 = ttng.tmem_load %res[%mma] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #blocked>
        "use"(%val) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #blocked>) -> ()
        scf.yield {ttg.partition = array<i32: 0, 1>} %t2 : !ttg.async.token
      } {ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 0>]}
      scf.yield {ttg.partition = array<i32: 0, 1>} %i : !ttg.async.token
    } {tt.warp_specialize, ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 0>], ttg.warp_specialize.tag = 0 : i32}
    tt.return
  }
}
