// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK: #[[$ATTR_0:.+]] = #ttg.blocked<{sizePerThread = [2], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
// CHECK: #[[$ATTR_1:.+]] = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [2, 16], warpsPerCTA = [4, 1], order = [1, 0]}>
// CHECK: #[[$ATTR_2:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_3:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_4:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_5:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_6:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_7:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_8:.+]] = #ttg.linear<{{.*}}>
// CHECK: #[[$ATTR_9:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_10:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
// CHECK: #[[$ATTR_11:.+]] = #ttg.shared_memory
// CHECK: #[[$ATTR_12:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
// CHECK: #[[$ATTR_13:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 1, colStride = 1>
// RUN: triton-opt %s -allow-unregistered-dialect --nvws-insert-semas | FileCheck %s
// RUN: env NVWS_INSERT_SEMA_DUMP_DAG=1 triton-opt %s -allow-unregistered-dialect --nvws-insert-semas 2>&1 >/dev/null | FileCheck %s --check-prefix=HOLD
//
// HOLD-RULE gate pinning: accumulator-class components stay GATED (carriers
// threading persistent outer loops / nested finals). Nested K/V descriptor
// buffers now use POINT-OF-USE in the inner loop and PASSTHROUGH_DROP in the
// enclosing persistent loop; stats stores stay POINT-OF-USE.
// HOLD: holdrule{c0:gated(region-crossing)}
// HOLD: holdrule{c0:gated(entry-sema-mismatch)}
// HOLD: holdrule{c0:gated(region-crossing)}
// HOLD: holdrule{c0:gated(entry-sema-mismatch)}
// HOLD: holdrule{c0:gated(trailing-use)}
// HOLD: holdrule{c0:gated(entry-consumed)}
// HOLD: holdrule{c0:gated(trailing-use)}
// HOLD: holdrule{c0:gated(entry-consumed)}
// HOLD: holdrule{c0:pointofuse->nvws.descriptor_load}
// HOLD: holdrule{c0:pointofuse->nvws.descriptor_load}
// HOLD: holdrule{c0:passthrough-drop}
// HOLD: holdrule{c0:pointofuse->nvws.descriptor_load}
// HOLD: holdrule{c0:passthrough-drop}
// HOLD: holdrule{c0:pointofuse->nvws.descriptor_load}
// HOLD: holdrule{c0:pointofuse->ttg.local_store}
// HOLD: holdrule{c0:pointofuse->ttg.local_store}

// Captured from meta-aws-logs/run-22may26-nvws-meta-tmem-crash/passes/
// 062-anonymous_VerifyWarpSpecializationPartitions.mlir — Meta flash
// attention forward (persistent) IR. Stripped of loc() attributes.
// Used as a high-coverage input for v4 insert-semas discovery +
// ACCESS DAG (and the full pipeline once later commits land).

#blocked = #ttg.blocked<{sizePerThread = [2], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#blocked1 = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [2, 16], warpsPerCTA = [4, 1], order = [1, 0]}>
#linear = #ttg.linear<{register = [[0, 1], [0, 2], [0, 4], [0, 8], [0, 16], [0, 32], [0, 64], [128, 0]], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[32, 0], [64, 0]], block = []}>
#linear1 = #ttg.linear<{register = [[0, 1], [0, 2], [0, 4], [0, 8], [0, 16], [0, 32], [0, 64]], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[32, 0], [64, 0]], block = []}>
#linear2 = #ttg.linear<{register = [[0, 0, 1], [0, 0, 2], [0, 0, 4], [0, 0, 8], [0, 0, 16], [0, 0, 32], [0, 1, 0], [128, 0, 0]], lane = [[1, 0, 0], [2, 0, 0], [4, 0, 0], [8, 0, 0], [16, 0, 0]], warp = [[32, 0, 0], [64, 0, 0]], block = []}>
#linear3 = #ttg.linear<{register = [[0, 1, 0], [0, 2, 0], [0, 4, 0], [0, 8, 0], [0, 16, 0], [0, 32, 0], [0, 0, 1], [128, 0, 0]], lane = [[1, 0, 0], [2, 0, 0], [4, 0, 0], [8, 0, 0], [16, 0, 0]], warp = [[32, 0, 0], [64, 0, 0]], block = []}>
#linear4 = #ttg.linear<{register = [[0, 1], [0, 2], [0, 4], [0, 8], [0, 16], [0, 32], [128, 0]], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[32, 0], [64, 0]], block = []}>
#linear5 = #ttg.linear<{register = [], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[32, 0], [64, 0]], block = []}>
#linear6 = #ttg.linear<{register = [], lane = [[1], [2], [4], [8], [16]], warp = [[32], [64]], block = []}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 1, colStride = 1>
#tmem1 = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
module attributes {"ttg.cluster-dim-x" = 1 : i32, "ttg.cluster-dim-y" = 1 : i32, "ttg.cluster-dim-z" = 1 : i32, ttg.max_reg_auto_ws = 152 : i32, ttg.maxnreg = 128 : i32, ttg.min_reg_auto_ws = 24 : i32, "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:100", "ttg.threads-per-warp" = 32 : i32} {
// CHECK-LABEL:   tt.func public @_attn_fwd_persist(
// CHECK-SAME:  %[[VAL_0:.*]]: f32, %[[VAL_1:.*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32 {tt.divisibility = 16 : i32}, %[[VAL_4:.*]]: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %[[VAL_5:.*]]: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %[[VAL_6:.*]]: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %[[VAL_7:.*]]: !tt.ptr<f16> {tt.divisibility = 16 : i32}) attributes {noinline = false} {
// CHECK:           %[[VAL_8:.*]] = arith.constant false
// CHECK:           %[[VAL_9:.*]] = arith.constant true
// CHECK:           %[[VAL_10:.*]] = arith.constant 64 : i32
// CHECK:           %[[VAL_11:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_12:.*]] = arith.constant 16384 : i32
// CHECK:           %[[VAL_13:.*]] = arith.constant 128 : i32
// CHECK:           %[[VAL_14:.*]] = arith.constant 128 : i64
// CHECK:           %[[VAL_15:.*]] = arith.constant 1 : i64
// CHECK:           %[[VAL_16:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_17:.*]] = arith.constant 256 : i32
// CHECK:           %[[VAL_18:.*]] = arith.constant 1.44269502 : f32
// CHECK:           %[[VAL_19:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:           %[[VAL_20:.*]] = arith.constant dense<0xFF800000> : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:           %[[VAL_21:.*]] = arith.constant dense<1.000000e+00> : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:           %[[VAL_22:.*]] = tt.get_program_id x : i32
// CHECK:           %[[VAL_23:.*]] = tt.get_num_programs x : i32
// CHECK:           %[[VAL_24:.*]] = arith.muli %[[VAL_2]], %[[VAL_10]] : i32
// CHECK:           %[[VAL_25:.*]] = arith.muli %[[VAL_24]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_26:.*]] = arith.divsi %[[VAL_25]], %[[VAL_23]] : i32
// CHECK:           %[[VAL_27:.*]] = arith.remsi %[[VAL_25]], %[[VAL_23]] : i32
// CHECK:           %[[VAL_28:.*]] = arith.cmpi slt, %[[VAL_22]], %[[VAL_27]] : i32
// CHECK:           %[[VAL_29:.*]] = scf.if %[[VAL_28]] -> (i32) {
// CHECK:             %[[VAL_30:.*]] = arith.addi %[[VAL_26]], %[[VAL_11]] : i32
// CHECK:             scf.yield %[[VAL_30]] : i32
// CHECK:           } else {
// CHECK:             scf.yield %[[VAL_26]] : i32
// CHECK:           }
// CHECK:           %[[VAL_31:.*]] = arith.muli %[[VAL_2]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_32:.*]] = arith.muli %[[VAL_31]], %[[VAL_12]] : i32
// CHECK:           %[[VAL_33:.*]] = tt.make_tensor_descriptor %[[VAL_4]], {{\[}}%[[VAL_32]], %[[VAL_13]]], {{\[}}%[[VAL_14]], %[[VAL_15]]] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>
// CHECK:           %[[VAL_34:.*]] = tt.make_tensor_descriptor %[[VAL_4]], {{\[}}%[[VAL_32]], %[[VAL_13]]], {{\[}}%[[VAL_14]], %[[VAL_15]]] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>
// CHECK:           %[[VAL_35:.*]] = tt.make_tensor_descriptor %[[VAL_5]], {{\[}}%[[VAL_32]], %[[VAL_13]]], {{\[}}%[[VAL_14]], %[[VAL_15]]] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>
// CHECK:           %[[VAL_36:.*]] = tt.make_tensor_descriptor %[[VAL_6]], {{\[}}%[[VAL_32]], %[[VAL_13]]], {{\[}}%[[VAL_14]], %[[VAL_15]]] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>
// CHECK:           %[[VAL_37:.*]] = tt.make_tensor_descriptor %[[VAL_7]], {{\[}}%[[VAL_32]], %[[VAL_13]]], {{\[}}%[[VAL_14]], %[[VAL_15]]] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>
// CHECK:           %[[VAL_38:.*]] = tt.make_tensor_descriptor %[[VAL_7]], {{\[}}%[[VAL_32]], %[[VAL_13]]], {{\[}}%[[VAL_14]], %[[VAL_15]]] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>
// CHECK:           %[[VAL_39:.*]] = arith.muli %[[VAL_3]], %[[VAL_12]] : i32
// CHECK:           %[[VAL_40:.*]] = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #[[$ATTR_0]]>
// CHECK:           %[[VAL_41:.*]] = tt.make_range {end = 256 : i32, start = 128 : i32} : tensor<128xi32, #[[$ATTR_0]]>
// CHECK:           %[[VAL_42:.*]] = arith.mulf %[[VAL_0]], %[[VAL_18]] : f32
// CHECK:           %[[VAL_43:.*]] = tt.splat %[[VAL_42]] : f32 -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:           %[[VAL_44:.*]] = tt.splat %[[VAL_42]] : f32 -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:           %[[VAL_45:.*]] = tt.splat %[[VAL_42]] : f32 -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:           %[[VAL_46:.*]] = tt.splat %[[VAL_42]] : f32 -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:           %[[VAL_47:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:           %[[VAL_48:.*]] = nvws.semaphore.create %[[VAL_47]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_49:.*]] = nvws.semaphore.create %[[VAL_47]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_50:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:           %[[VAL_51:.*]] = nvws.semaphore.create %[[VAL_50]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_52:.*]] = nvws.semaphore.create %[[VAL_50]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_53:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:           %[[VAL_54:.*]] = nvws.semaphore.create %[[VAL_53]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_55:.*]] = nvws.semaphore.create %[[VAL_53]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_56:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:           %[[VAL_57:.*]] = nvws.semaphore.create %[[VAL_56]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_58:.*]] = nvws.semaphore.create %[[VAL_56]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_59:.*]] = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 4 : i32, buffer.offset = 0 : i32} : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_60:.*]] = ttng.tmem_subslice %[[VAL_59]] {N = 0 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_61:.*]] = ttg.memdesc_reinterpret %[[VAL_60]] : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_62:.*]] = ttng.tmem_subslice %[[VAL_59]] {N = 65 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_63:.*]] = ttg.memdesc_reinterpret %[[VAL_62]] : !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_64:.*]] = ttng.tmem_subslice %[[VAL_59]] {N = 66 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_65:.*]] = ttg.memdesc_reinterpret %[[VAL_64]] : !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_66:.*]] = ttng.tmem_subslice %[[VAL_59]] {N = 64 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_67:.*]] = ttg.memdesc_reinterpret %[[VAL_66]] : !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_68:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] true {pending_count = 2 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_69:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_70:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_71:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_72:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_73:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 2 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_74:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_75:.*]] = nvws.semaphore.create %[[VAL_67]], %[[VAL_65]], %[[VAL_63]], %[[VAL_59]], %[[VAL_61]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_76:.*]] = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 5 : i32, buffer.offset = 0 : i32} : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_77:.*]] = ttng.tmem_subslice %[[VAL_76]] {N = 0 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_78:.*]] = ttg.memdesc_reinterpret %[[VAL_77]] : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_79:.*]] = ttng.tmem_subslice %[[VAL_76]] {N = 65 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_80:.*]] = ttg.memdesc_reinterpret %[[VAL_79]] : !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_81:.*]] = ttng.tmem_subslice %[[VAL_76]] {N = 66 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_82:.*]] = ttg.memdesc_reinterpret %[[VAL_81]] : !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_83:.*]] = ttng.tmem_subslice %[[VAL_76]] {N = 64 : i32} : !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_84:.*]] = ttg.memdesc_reinterpret %[[VAL_83]] : !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x128> -> !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_85:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] true {pending_count = 2 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_86:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_87:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_88:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_89:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_90:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 2 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_91:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_92:.*]] = nvws.semaphore.create %[[VAL_84]], %[[VAL_82]], %[[VAL_80]], %[[VAL_76]], %[[VAL_78]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_93:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:           %[[VAL_94:.*]] = nvws.semaphore.create %[[VAL_93]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_95:.*]] = nvws.semaphore.create %[[VAL_93]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_96:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:           %[[VAL_97:.*]] = nvws.semaphore.create %[[VAL_96]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_98:.*]] = nvws.semaphore.create %[[VAL_96]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>
// CHECK:           %[[VAL_99:.*]] = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 2 : i32, buffer.offset = 0 : i32} : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_100:.*]] = nvws.semaphore.create %[[VAL_99]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_101:.*]] = nvws.semaphore.create %[[VAL_99]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_102:.*]] = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 3 : i32, buffer.offset = 0 : i32} : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_103:.*]] = nvws.semaphore.create %[[VAL_102]] true {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_104:.*]] = nvws.semaphore.create %[[VAL_102]] false {pending_count = 1 : i32} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>
// CHECK:           %[[VAL_105:.*]] = nvws.semaphore.acquire %[[VAL_68]] : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:           %[[VAL_106:.*]] = nvws.semaphore.acquire %[[VAL_85]] : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:           %[[VAL_107:.*]] = nvws.semaphore.acquire %[[VAL_100]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:           %[[VAL_108:.*]] = nvws.semaphore.acquire %[[VAL_103]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:           %[[VAL_109:.*]]:5 = scf.for %[[VAL_110:.*]] = %[[VAL_16]] to %[[VAL_29]] step %[[VAL_11]] iter_args(%[[VAL_111:.*]] = %[[VAL_22]], %[[VAL_112:.*]] = %[[VAL_105]], %[[VAL_113:.*]] = %[[VAL_106]], %[[VAL_114:.*]] = %[[VAL_107]], %[[VAL_115:.*]] = %[[VAL_108]]) -> (i32, !ttg.async.token, !ttg.async.token, !ttg.async.token, !ttg.async.token)  : i32 {
// CHECK:             %[[VAL_116:.*]] = arith.remsi %[[VAL_111]], %[[VAL_10]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_117:.*]] = arith.divsi %[[VAL_111]], %[[VAL_10]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_118:.*]] = arith.divsi %[[VAL_117]], %[[VAL_3]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_119:.*]] = arith.remsi %[[VAL_117]], %[[VAL_3]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_120:.*]] = arith.muli %[[VAL_118]], %[[VAL_39]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_121:.*]] = arith.muli %[[VAL_119]], %[[VAL_12]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_122:.*]] = arith.addi %[[VAL_120]], %[[VAL_121]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_123:.*]] = arith.muli %[[VAL_116]], %[[VAL_17]] {ttg.partition = array<i32: 0, 2, 3>} : i32
// CHECK:             %[[VAL_124:.*]] = arith.addi %[[VAL_122]], %[[VAL_123]] {ttg.partition = array<i32: 2, 3>} : i32
// CHECK:             %[[VAL_125:.*]] = arith.addi %[[VAL_124]], %[[VAL_13]] {ttg.partition = array<i32: 2>} : i32
// CHECK:             %[[VAL_126:.*]] = arith.addi %[[VAL_124]], %[[VAL_13]] {ttg.partition = array<i32: 3>} : i32
// CHECK:             %[[VAL_127:.*]] = tt.splat %[[VAL_123]] {ttg.partition = array<i32: 0, 2, 3>} : i32 -> tensor<128xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_128:.*]] = tt.splat %[[VAL_123]] {ttg.partition = array<i32: 0, 2, 3>} : i32 -> tensor<128xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_129:.*]] = arith.addi %[[VAL_127]], %[[VAL_40]] {ttg.partition = array<i32: 0>} : tensor<128xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_130:.*]] = arith.addi %[[VAL_128]], %[[VAL_41]] {ttg.partition = array<i32: 0>} : tensor<128xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_131:.*]] = nvws.semaphore.acquire %[[VAL_48]] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_132:.*]] = nvws.semaphore.buffer %[[VAL_48]], %[[VAL_131]] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             nvws.descriptor_load %[[VAL_33]]{{\[}}%[[VAL_124]], %[[VAL_16]]] 32768 %[[VAL_132]] {ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>, i32, i32, !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_49]], %[[VAL_131]] [#nvws.async_op<tma_load>] {arrive_count = 1 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_133:.*]] = nvws.semaphore.acquire %[[VAL_51]] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_134:.*]] = nvws.semaphore.buffer %[[VAL_51]], %[[VAL_133]] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             nvws.descriptor_load %[[VAL_34]]{{\[}}%[[VAL_126]], %[[VAL_16]]] 32768 %[[VAL_134]] {ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>, i32, i32, !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_52]], %[[VAL_133]] [#nvws.async_op<tma_load>] {arrive_count = 1 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_135:.*]] = nvws.semaphore.buffer %[[VAL_100]], %[[VAL_114]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_136:.*]] = arith.constant {ttg.partition = array<i32: 0>} true
// CHECK:             ttng.tmem_store %[[VAL_19]], %[[VAL_135]], %[[VAL_136]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_137:.*]] = nvws.semaphore.buffer %[[VAL_103]], %[[VAL_115]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_138:.*]] = arith.constant {ttg.partition = array<i32: 0>} true
// CHECK:             ttng.tmem_store %[[VAL_19]], %[[VAL_137]], %[[VAL_138]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_139:.*]] = nvws.semaphore.acquire %[[VAL_49]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_140:.*]] = nvws.semaphore.acquire %[[VAL_52]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_141:.*]]:9 = scf.for %[[VAL_142:.*]] = %[[VAL_16]] to %[[VAL_12]] step %[[VAL_13]] iter_args(%[[VAL_143:.*]] = %[[VAL_122]], %[[VAL_144:.*]] = %[[VAL_21]], %[[VAL_145:.*]] = %[[VAL_20]], %[[VAL_146:.*]] = %[[VAL_21]], %[[VAL_147:.*]] = %[[VAL_20]], %[[VAL_148:.*]] = %[[VAL_112]], %[[VAL_149:.*]] = %[[VAL_113]], %[[VAL_150:.*]] = %[[VAL_114]], %[[VAL_151:.*]] = %[[VAL_115]]) -> (i32, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, !ttg.async.token, !ttg.async.token, !ttg.async.token, !ttg.async.token)  : i32 {
// CHECK:               %[[VAL_152:.*]] = nvws.semaphore.acquire %[[VAL_54]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_153:.*]] = nvws.semaphore.buffer %[[VAL_54]], %[[VAL_152]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               nvws.descriptor_load %[[VAL_35]]{{\[}}%[[VAL_143]], %[[VAL_16]]] 32768 %[[VAL_153]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>, i32, i32, !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               nvws.semaphore.release %[[VAL_55]], %[[VAL_152]] [#nvws.async_op<tma_load>] {arrive_count = 1 : i32, loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_154:.*]] = nvws.semaphore.acquire %[[VAL_57]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_155:.*]] = nvws.semaphore.buffer %[[VAL_57]], %[[VAL_154]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               nvws.descriptor_load %[[VAL_36]]{{\[}}%[[VAL_143]], %[[VAL_16]]] 32768 %[[VAL_155]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>, i32, i32, !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               nvws.semaphore.release %[[VAL_58]], %[[VAL_154]] [#nvws.async_op<tma_load>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_156:.*]]:5 = nvws.semaphore.buffer %[[VAL_68]], %[[VAL_148]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_157:.*]] = nvws.semaphore.buffer %[[VAL_49]], %[[VAL_139]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_158:.*]] = nvws.semaphore.acquire %[[VAL_55]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_159:.*]] = nvws.semaphore.buffer %[[VAL_55]], %[[VAL_158]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_160:.*]] = ttg.memdesc_reinterpret %[[VAL_159]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable> -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_161:.*]] = ttg.memdesc_trans %[[VAL_160]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable> -> !ttg.memdesc<128x128xf16, #[[$ATTR_10]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_162:.*]] = ttng.tc_gen5_mma %[[VAL_157]], %[[VAL_161]], %[[VAL_156]]#3[], %[[VAL_8]], %[[VAL_9]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>, !ttg.memdesc<128x128xf16, #[[$ATTR_10]], #[[$ATTR_11]], mutable>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_69]], %[[VAL_148]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               nvws.semaphore.release %[[VAL_71]], %[[VAL_148]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_163:.*]]:5 = nvws.semaphore.buffer %[[VAL_85]], %[[VAL_149]] {loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_164:.*]] = nvws.semaphore.buffer %[[VAL_52]], %[[VAL_140]] {loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_165:.*]] = ttg.memdesc_reinterpret %[[VAL_159]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable> -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_166:.*]] = ttg.memdesc_trans %[[VAL_165]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable> -> !ttg.memdesc<128x128xf16, #[[$ATTR_10]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_167:.*]] = ttng.tc_gen5_mma %[[VAL_164]], %[[VAL_166]], %[[VAL_163]]#3[], %[[VAL_8]], %[[VAL_9]] {loop.cluster = 3 : i32, loop.stage = 0 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>, !ttg.memdesc<128x128xf16, #[[$ATTR_10]], #[[$ATTR_11]], mutable>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_54]], %[[VAL_158]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:               nvws.semaphore.release %[[VAL_86]], %[[VAL_149]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               nvws.semaphore.release %[[VAL_88]], %[[VAL_149]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_168:.*]] = nvws.semaphore.acquire %[[VAL_69]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_169:.*]]:5 = nvws.semaphore.buffer %[[VAL_69]], %[[VAL_168]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_170:.*]], %[[VAL_171:.*]] = ttng.tmem_load %[[VAL_169]]#3[] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_3]]>
// CHECK:               %[[VAL_172:.*]] = ttg.convert_layout %[[VAL_170]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #[[$ATTR_3]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_173:.*]] = nvws.semaphore.acquire %[[VAL_86]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_174:.*]]:5 = nvws.semaphore.buffer %[[VAL_86]], %[[VAL_173]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_175:.*]], %[[VAL_176:.*]] = ttng.tmem_load %[[VAL_174]]#3[] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_3]]>
// CHECK:               %[[VAL_177:.*]] = ttg.convert_layout %[[VAL_175]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #[[$ATTR_3]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_178:.*]] = "tt.reduce"(%[[VAL_172]]) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
// CHECK:               ^bb0(%[[VAL_179:.*]]: f32, %[[VAL_180:.*]]: f32):
// CHECK:                 %[[VAL_181:.*]] = arith.maxnumf %[[VAL_179]], %[[VAL_180]] {ttg.partition = array<i32: 5>} : f32
// CHECK:                 tt.reduce.return %[[VAL_181]] {ttg.partition = array<i32: 5>} : f32
// CHECK:               }) {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>, ttg.partition.outputs = [array<i32: 5>]} : (tensor<128x128xf32, #[[$ATTR_2]]>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_182:.*]] = "tt.reduce"(%[[VAL_177]]) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
// CHECK:               ^bb0(%[[VAL_183:.*]]: f32, %[[VAL_184:.*]]: f32):
// CHECK:                 %[[VAL_185:.*]] = arith.maxnumf %[[VAL_183]], %[[VAL_184]] {ttg.partition = array<i32: 4>} : f32
// CHECK:                 tt.reduce.return %[[VAL_185]] {ttg.partition = array<i32: 4>} : f32
// CHECK:               }) {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>, ttg.partition.outputs = [array<i32: 4>]} : (tensor<128x128xf32, #[[$ATTR_2]]>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_186:.*]] = arith.mulf %[[VAL_178]], %[[VAL_43]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_187:.*]] = arith.mulf %[[VAL_182]], %[[VAL_44]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_188:.*]] = arith.maxnumf %[[VAL_145]], %[[VAL_186]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_189:.*]] = arith.maxnumf %[[VAL_147]], %[[VAL_187]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_190:.*]] = arith.mulf %[[VAL_172]], %[[VAL_45]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_191:.*]] = arith.mulf %[[VAL_177]], %[[VAL_46]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_192:.*]] = tt.expand_dims %[[VAL_188]] {axis = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_193:.*]] = tt.expand_dims %[[VAL_189]] {axis = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_194:.*]] = tt.broadcast %[[VAL_192]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x1xf32, #[[$ATTR_2]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_195:.*]] = tt.broadcast %[[VAL_193]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x1xf32, #[[$ATTR_2]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_196:.*]] = arith.subf %[[VAL_190]], %[[VAL_194]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_197:.*]] = arith.subf %[[VAL_191]], %[[VAL_195]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_198:.*]] = math.exp2 %[[VAL_196]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_199:.*]] = math.exp2 %[[VAL_197]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_200:.*]] = arith.subf %[[VAL_145]], %[[VAL_188]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_201:.*]] = arith.subf %[[VAL_147]], %[[VAL_189]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_202:.*]] = math.exp2 %[[VAL_200]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_203:.*]] = tt.expand_dims %[[VAL_202]] {axis = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_204:.*]] = arith.constant {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} true
// CHECK:               ttng.tmem_store %[[VAL_203]], %[[VAL_169]]#0, %[[VAL_204]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x1xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>
// CHECK:               nvws.semaphore.release %[[VAL_70]], %[[VAL_168]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               nvws.semaphore.release %[[VAL_73]], %[[VAL_168]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_205:.*]] = math.exp2 %[[VAL_201]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_206:.*]] = tt.expand_dims %[[VAL_205]] {axis = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_207:.*]] = arith.constant {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} true
// CHECK:               ttng.tmem_store %[[VAL_206]], %[[VAL_174]]#0, %[[VAL_207]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x1xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>
// CHECK:               nvws.semaphore.release %[[VAL_87]], %[[VAL_173]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               nvws.semaphore.release %[[VAL_90]], %[[VAL_173]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_208:.*]] = "tt.reduce"(%[[VAL_198]]) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
// CHECK:               ^bb0(%[[VAL_209:.*]]: f32, %[[VAL_210:.*]]: f32):
// CHECK:                 %[[VAL_211:.*]] = arith.addf %[[VAL_209]], %[[VAL_210]] {ttg.partition = array<i32: 5>} : f32
// CHECK:                 tt.reduce.return %[[VAL_211]] {ttg.partition = array<i32: 5>} : f32
// CHECK:               }) {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 5>, ttg.partition.outputs = [array<i32: 5>]} : (tensor<128x128xf32, #[[$ATTR_2]]>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_212:.*]] = "tt.reduce"(%[[VAL_199]]) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
// CHECK:               ^bb0(%[[VAL_213:.*]]: f32, %[[VAL_214:.*]]: f32):
// CHECK:                 %[[VAL_215:.*]] = arith.addf %[[VAL_213]], %[[VAL_214]] {ttg.partition = array<i32: 4>} : f32
// CHECK:                 tt.reduce.return %[[VAL_215]] {ttg.partition = array<i32: 4>} : f32
// CHECK:               }) {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>, ttg.partition.outputs = [array<i32: 4>]} : (tensor<128x128xf32, #[[$ATTR_2]]>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_216:.*]] = nvws.semaphore.buffer %[[VAL_100]], %[[VAL_150]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_217:.*]], %[[VAL_218:.*]] = ttng.tmem_load %[[VAL_216]][] {loop.cluster = 4 : i32, loop.stage = 0 : i32, tmem.end = array<i32: 8>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_3]]>
// CHECK:               %[[VAL_219:.*]] = nvws.semaphore.buffer %[[VAL_103]], %[[VAL_151]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_220:.*]], %[[VAL_221:.*]] = ttng.tmem_load %[[VAL_219]][] {loop.cluster = 2 : i32, loop.stage = 1 : i32, tmem.end = array<i32: 11>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_3]]>
// CHECK:               %[[VAL_222:.*]] = tt.reshape %[[VAL_217]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_3]]> -> tensor<128x2x64xf32, #[[$ATTR_4]]>
// CHECK:               %[[VAL_223:.*]] = tt.reshape %[[VAL_220]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_3]]> -> tensor<128x2x64xf32, #[[$ATTR_4]]>
// CHECK:               %[[VAL_224:.*]] = tt.trans %[[VAL_222]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #[[$ATTR_4]]> -> tensor<128x64x2xf32, #[[$ATTR_5]]>
// CHECK:               %[[VAL_225:.*]] = tt.trans %[[VAL_223]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #[[$ATTR_4]]> -> tensor<128x64x2xf32, #[[$ATTR_5]]>
// CHECK:               %[[VAL_226:.*]], %[[VAL_227:.*]] = tt.split %[[VAL_224]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #[[$ATTR_5]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_228:.*]], %[[VAL_229:.*]] = tt.split %[[VAL_225]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #[[$ATTR_5]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_230:.*]] = nvws.semaphore.acquire %[[VAL_70]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_231:.*]]:5 = nvws.semaphore.buffer %[[VAL_70]], %[[VAL_230]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_232:.*]], %[[VAL_233:.*]] = ttng.tmem_load %[[VAL_231]]#0[] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1> -> tensor<128x1xf32, #[[$ATTR_7]]>
// CHECK:               nvws.semaphore.release %[[VAL_73]], %[[VAL_230]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_234:.*]] = tt.reshape %[[VAL_232]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_7]]> -> tensor<128xf32, #[[$ATTR_8]]>
// CHECK:               %[[VAL_235:.*]] = ttg.convert_layout %[[VAL_234]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #[[$ATTR_8]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_236:.*]] = tt.expand_dims %[[VAL_235]] {axis = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_237:.*]] = nvws.semaphore.acquire %[[VAL_87]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_238:.*]]:5 = nvws.semaphore.buffer %[[VAL_87]], %[[VAL_237]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_239:.*]], %[[VAL_240:.*]] = ttng.tmem_load %[[VAL_238]]#0[] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1> -> tensor<128x1xf32, #[[$ATTR_7]]>
// CHECK:               nvws.semaphore.release %[[VAL_90]], %[[VAL_237]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_241:.*]] = tt.reshape %[[VAL_239]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_7]]> -> tensor<128xf32, #[[$ATTR_8]]>
// CHECK:               %[[VAL_242:.*]] = ttg.convert_layout %[[VAL_241]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #[[$ATTR_8]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_243:.*]] = tt.expand_dims %[[VAL_242]] {axis = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_244:.*]] = ttg.convert_layout %[[VAL_236]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_2]]> -> tensor<128x1xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_245:.*]] = ttg.convert_layout %[[VAL_243]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_2]]> -> tensor<128x1xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_246:.*]] = tt.broadcast %[[VAL_244]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_6]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_247:.*]] = tt.broadcast %[[VAL_245]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_6]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_248:.*]] = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 4 : i32, loop.stage = 0 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %[[VAL_226]], %[[VAL_246]] : tensor<128x64xf32, #[[$ATTR_6]]>, tensor<128x64xf32, #[[$ATTR_6]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_249:.*]] = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 2 : i32, loop.stage = 1 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %[[VAL_228]], %[[VAL_247]] : tensor<128x64xf32, #[[$ATTR_6]]>, tensor<128x64xf32, #[[$ATTR_6]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_250:.*]] = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 4 : i32, loop.stage = 0 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %[[VAL_227]], %[[VAL_246]] : tensor<128x64xf32, #[[$ATTR_6]]>, tensor<128x64xf32, #[[$ATTR_6]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_251:.*]] = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 2 : i32, loop.stage = 1 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %[[VAL_229]], %[[VAL_247]] : tensor<128x64xf32, #[[$ATTR_6]]>, tensor<128x64xf32, #[[$ATTR_6]]> -> tensor<128x64xf32, #[[$ATTR_6]]>
// CHECK:               %[[VAL_252:.*]] = tt.join %[[VAL_248]], %[[VAL_250]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x64xf32, #[[$ATTR_6]]> -> tensor<128x64x2xf32, #[[$ATTR_5]]>
// CHECK:               %[[VAL_253:.*]] = tt.join %[[VAL_249]], %[[VAL_251]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x64xf32, #[[$ATTR_6]]> -> tensor<128x64x2xf32, #[[$ATTR_5]]>
// CHECK:               %[[VAL_254:.*]] = tt.trans %[[VAL_252]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #[[$ATTR_5]]> -> tensor<128x2x64xf32, #[[$ATTR_4]]>
// CHECK:               %[[VAL_255:.*]] = tt.trans %[[VAL_253]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #[[$ATTR_5]]> -> tensor<128x2x64xf32, #[[$ATTR_4]]>
// CHECK:               %[[VAL_256:.*]] = tt.reshape %[[VAL_254]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #[[$ATTR_4]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_257:.*]] = tt.reshape %[[VAL_255]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #[[$ATTR_4]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:               %[[VAL_258:.*]] = arith.truncf %[[VAL_198]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #[[$ATTR_2]]> to tensor<128x128xf16, #[[$ATTR_2]]>
// CHECK:               %[[VAL_259:.*]] = arith.truncf %[[VAL_199]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #[[$ATTR_2]]> to tensor<128x128xf16, #[[$ATTR_2]]>
// CHECK:               %[[VAL_260:.*]] = nvws.semaphore.acquire %[[VAL_71]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_261:.*]]:5 = nvws.semaphore.buffer %[[VAL_71]], %[[VAL_260]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_262:.*]] = arith.constant {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} true
// CHECK:               ttng.tmem_store %[[VAL_258]], %[[VAL_261]]#4, %[[VAL_262]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf16, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_72]], %[[VAL_260]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_263:.*]] = nvws.semaphore.acquire %[[VAL_88]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_264:.*]]:5 = nvws.semaphore.buffer %[[VAL_88]], %[[VAL_263]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_265:.*]] = arith.constant {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} true
// CHECK:               ttng.tmem_store %[[VAL_259]], %[[VAL_264]]#4, %[[VAL_265]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf16, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_89]], %[[VAL_263]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_266:.*]] = ttng.tmem_store %[[VAL_256]], %[[VAL_216]][], %[[VAL_9]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, tmem.start = array<i32: 9>, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_101]], %[[VAL_150]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_267:.*]] = ttng.tmem_store %[[VAL_257]], %[[VAL_219]][], %[[VAL_9]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, tmem.start = array<i32: 12>, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_104]], %[[VAL_151]] [#nvws.async_op<none>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_268:.*]] = nvws.semaphore.acquire %[[VAL_72]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_269:.*]]:5 = nvws.semaphore.buffer %[[VAL_72]], %[[VAL_268]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_270:.*]] = nvws.semaphore.acquire %[[VAL_101]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_271:.*]] = nvws.semaphore.buffer %[[VAL_101]], %[[VAL_270]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_272:.*]] = nvws.semaphore.acquire %[[VAL_58]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_273:.*]] = nvws.semaphore.buffer %[[VAL_58]], %[[VAL_272]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:               %[[VAL_274:.*]] = ttng.tc_gen5_mma %[[VAL_269]]#4, %[[VAL_273]], %[[VAL_271]][], %[[VAL_9]], %[[VAL_9]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, tmem.end = array<i32: 9>, tmem.start = array<i32: 8, 10>, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_100]], %[[VAL_270]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_275:.*]] = nvws.semaphore.acquire %[[VAL_89]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_276:.*]]:5 = nvws.semaphore.buffer %[[VAL_89]], %[[VAL_275]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_277:.*]] = nvws.semaphore.acquire %[[VAL_104]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_278:.*]] = nvws.semaphore.buffer %[[VAL_104]], %[[VAL_277]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               %[[VAL_279:.*]] = ttng.tc_gen5_mma %[[VAL_276]]#4, %[[VAL_273]], %[[VAL_278]][], %[[VAL_9]], %[[VAL_9]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, tmem.end = array<i32: 12>, tmem.start = array<i32: 11, 13>, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:               nvws.semaphore.release %[[VAL_57]], %[[VAL_272]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:               nvws.semaphore.release %[[VAL_103]], %[[VAL_277]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:               %[[VAL_280:.*]] = arith.mulf %[[VAL_144]], %[[VAL_202]] {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_281:.*]] = arith.mulf %[[VAL_146]], %[[VAL_205]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_282:.*]] = arith.addf %[[VAL_280]], %[[VAL_208]] {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_283:.*]] = arith.addf %[[VAL_281]], %[[VAL_212]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:               %[[VAL_284:.*]] = arith.addi %[[VAL_143]], %[[VAL_13]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 3>} : i32
// CHECK:               %[[VAL_285:.*]] = nvws.semaphore.acquire %[[VAL_73]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_286:.*]] = nvws.semaphore.acquire %[[VAL_90]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_287:.*]] = nvws.semaphore.acquire %[[VAL_100]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               %[[VAL_288:.*]] = nvws.semaphore.acquire %[[VAL_103]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:               scf.yield {ttg.partition = array<i32: 0, 1, 3, 4, 5>} %[[VAL_284]], %[[VAL_282]], %[[VAL_188]], %[[VAL_283]], %[[VAL_189]], %[[VAL_285]], %[[VAL_286]], %[[VAL_287]], %[[VAL_288]] : i32, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>, !ttg.async.token, !ttg.async.token, !ttg.async.token, !ttg.async.token
// CHECK:             } {tt.data_partition_factor = 2 : i32, tt.merge_epilogue = true, tt.scheduled_max_stage = 1 : i32, tt.separate_epilogue_store = true, ttg.partition = array<i32: 0, 1, 3, 4, 5>, ttg.partition.outputs = [array<i32: 3>, array<i32: 5>, array<i32: 5>, array<i32: 4>, array<i32: 4>, array<i32: 1>, array<i32: 1>, array<i32: 0>, array<i32: 0>]}
// CHECK:             nvws.semaphore.release %[[VAL_51]], %[[VAL_140]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_48]], %[[VAL_139]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_91]], %[[VAL_289:.*]]#6 [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_74]], %[[VAL_289]]#5 [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_290:.*]] = tt.expand_dims %[[VAL_289]]#4 {axis = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_291:.*]] = arith.constant {ttg.partition = array<i32: 4>} true
// CHECK:             %[[VAL_292:.*]] = nvws.semaphore.acquire %[[VAL_91]] {ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_293:.*]]:5 = nvws.semaphore.buffer %[[VAL_91]], %[[VAL_292]] {ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             ttng.tmem_store %[[VAL_290]], %[[VAL_293]]#2, %[[VAL_291]] {ttg.partition = array<i32: 4>} : tensor<128x1xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>
// CHECK:             %[[VAL_294:.*]] = tt.expand_dims %[[VAL_289]]#3 {axis = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_295:.*]] = arith.constant {ttg.partition = array<i32: 4>} true
// CHECK:             ttng.tmem_store %[[VAL_294]], %[[VAL_293]]#1, %[[VAL_295]] {ttg.partition = array<i32: 4>} : tensor<128x1xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>
// CHECK:             nvws.semaphore.release %[[VAL_92]], %[[VAL_292]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_85]], %[[VAL_292]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 4>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_296:.*]] = tt.expand_dims %[[VAL_289]]#2 {axis = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_297:.*]] = arith.constant {ttg.partition = array<i32: 5>} true
// CHECK:             %[[VAL_298:.*]] = nvws.semaphore.acquire %[[VAL_74]] {ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_299:.*]]:5 = nvws.semaphore.buffer %[[VAL_74]], %[[VAL_298]] {ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             ttng.tmem_store %[[VAL_296]], %[[VAL_299]]#2, %[[VAL_297]] {ttg.partition = array<i32: 5>} : tensor<128x1xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>
// CHECK:             %[[VAL_300:.*]] = tt.expand_dims %[[VAL_289]]#1 {axis = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_301:.*]] = arith.constant {ttg.partition = array<i32: 5>} true
// CHECK:             ttng.tmem_store %[[VAL_300]], %[[VAL_299]]#1, %[[VAL_301]] {ttg.partition = array<i32: 5>} : tensor<128x1xf32, #[[$ATTR_2]]> -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>
// CHECK:             nvws.semaphore.release %[[VAL_75]], %[[VAL_298]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_68]], %[[VAL_298]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 5>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_302:.*]] = nvws.semaphore.acquire %[[VAL_75]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_303:.*]]:5 = nvws.semaphore.buffer %[[VAL_75]], %[[VAL_302]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_304:.*]], %[[VAL_305:.*]] = ttng.tmem_load %[[VAL_303]]#1[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1> -> tensor<128x1xf32, #[[$ATTR_7]]>
// CHECK:             %[[VAL_306:.*]] = tt.reshape %[[VAL_304]] {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_7]]> -> tensor<128xf32, #[[$ATTR_8]]>
// CHECK:             %[[VAL_307:.*]] = ttg.convert_layout %[[VAL_306]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #[[$ATTR_8]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_308:.*]] = math.log2 %[[VAL_307]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_309:.*]] = nvws.semaphore.acquire %[[VAL_92]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_310:.*]]:5 = nvws.semaphore.buffer %[[VAL_92]], %[[VAL_309]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1>, !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_311:.*]], %[[VAL_312:.*]] = ttng.tmem_load %[[VAL_310]]#1[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1> -> tensor<128x1xf32, #[[$ATTR_7]]>
// CHECK:             %[[VAL_313:.*]] = tt.reshape %[[VAL_311]] {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_7]]> -> tensor<128xf32, #[[$ATTR_8]]>
// CHECK:             %[[VAL_314:.*]] = ttg.convert_layout %[[VAL_313]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #[[$ATTR_8]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_315:.*]] = math.log2 %[[VAL_314]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_316:.*]], %[[VAL_317:.*]] = ttng.tmem_load %[[VAL_303]]#2[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1> -> tensor<128x1xf32, #[[$ATTR_7]]>
// CHECK:             nvws.semaphore.release %[[VAL_68]], %[[VAL_302]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_318:.*]] = tt.reshape %[[VAL_316]] {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_7]]> -> tensor<128xf32, #[[$ATTR_8]]>
// CHECK:             %[[VAL_319:.*]] = ttg.convert_layout %[[VAL_318]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #[[$ATTR_8]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_320:.*]] = arith.addf %[[VAL_319]], %[[VAL_308]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_321:.*]], %[[VAL_322:.*]] = ttng.tmem_load %[[VAL_310]]#2[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable, 1x128x1> -> tensor<128x1xf32, #[[$ATTR_7]]>
// CHECK:             nvws.semaphore.release %[[VAL_85]], %[[VAL_309]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_323:.*]] = tt.reshape %[[VAL_321]] {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_7]]> -> tensor<128xf32, #[[$ATTR_8]]>
// CHECK:             %[[VAL_324:.*]] = ttg.convert_layout %[[VAL_323]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #[[$ATTR_8]]> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_325:.*]] = arith.addf %[[VAL_324]], %[[VAL_315]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>>
// CHECK:             %[[VAL_326:.*]] = tt.expand_dims %[[VAL_307]] {axis = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_327:.*]] = tt.expand_dims %[[VAL_314]] {axis = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128x1xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_328:.*]] = tt.broadcast %[[VAL_326]] {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_2]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_329:.*]] = tt.broadcast %[[VAL_327]] {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #[[$ATTR_2]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_330:.*]] = nvws.semaphore.buffer %[[VAL_100]], %[[VAL_289]]#7 {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_331:.*]], %[[VAL_332:.*]] = ttng.tmem_load %[[VAL_330]][] {tmem.end = array<i32: 10>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_3]]>
// CHECK:             %[[VAL_333:.*]] = ttg.convert_layout %[[VAL_331]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_3]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_334:.*]] = nvws.semaphore.buffer %[[VAL_103]], %[[VAL_289]]#8 {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_335:.*]], %[[VAL_336:.*]] = ttng.tmem_load %[[VAL_334]][] {tmem.end = array<i32: 13>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_3]]>
// CHECK:             %[[VAL_337:.*]] = ttg.convert_layout %[[VAL_335]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_3]]> -> tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_338:.*]] = arith.divf %[[VAL_333]], %[[VAL_328]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_339:.*]] = arith.divf %[[VAL_337]], %[[VAL_329]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]>
// CHECK:             %[[VAL_340:.*]] = arith.muli %[[VAL_117]], %[[VAL_12]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_341:.*]] = tt.addptr %[[VAL_1]], %[[VAL_340]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : !tt.ptr<f32>, i32
// CHECK:             %[[VAL_342:.*]] = tt.splat %[[VAL_341]] {ttg.partition = array<i32: 0>} : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>, #[[$ATTR_0]]>
// CHECK:             %[[VAL_343:.*]] = tt.splat %[[VAL_341]] {ttg.partition = array<i32: 0>} : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>, #[[$ATTR_0]]>
// CHECK:             %[[VAL_344:.*]] = tt.addptr %[[VAL_342]], %[[VAL_129]] {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #[[$ATTR_0]]>, tensor<128xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_345:.*]] = tt.addptr %[[VAL_343]], %[[VAL_130]] {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #[[$ATTR_0]]>, tensor<128xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_346:.*]] = ttg.convert_layout %[[VAL_320]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128xf32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_347:.*]] = ttg.convert_layout %[[VAL_325]] {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_2]]}>> -> tensor<128xf32, #[[$ATTR_0]]>
// CHECK:             tt.store %[[VAL_344]], %[[VAL_346]] {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #[[$ATTR_0]]>
// CHECK:             tt.store %[[VAL_345]], %[[VAL_347]] {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #[[$ATTR_0]]>
// CHECK:             %[[VAL_348:.*]] = arith.truncf %[[VAL_338]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]> to tensor<128x128xf16, #[[$ATTR_2]]>
// CHECK:             %[[VAL_349:.*]] = nvws.semaphore.acquire %[[VAL_94]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_350:.*]] = nvws.semaphore.buffer %[[VAL_94]], %[[VAL_349]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             ttg.local_store %[[VAL_348]], %[[VAL_350]] {ttg.partition = array<i32: 0>} : tensor<128x128xf16, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_95]], %[[VAL_349]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_351:.*]] = arith.truncf %[[VAL_339]] {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #[[$ATTR_2]]> to tensor<128x128xf16, #[[$ATTR_2]]>
// CHECK:             %[[VAL_352:.*]] = nvws.semaphore.acquire %[[VAL_97]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_353:.*]] = nvws.semaphore.buffer %[[VAL_97]], %[[VAL_352]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             ttg.local_store %[[VAL_351]], %[[VAL_353]] {ttg.partition = array<i32: 0>} : tensor<128x128xf16, #[[$ATTR_2]]> -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_98]], %[[VAL_352]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_354:.*]] = nvws.semaphore.acquire %[[VAL_95]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_355:.*]] = nvws.semaphore.buffer %[[VAL_95]], %[[VAL_354]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             %[[VAL_356:.*]] = ttg.local_load %[[VAL_355]] {ttg.partition = array<i32: 2>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable> -> tensor<128x128xf16, #[[$ATTR_2]]>
// CHECK:             nvws.semaphore.release %[[VAL_94]], %[[VAL_354]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_357:.*]] = ttg.convert_layout %[[VAL_356]] {ttg.partition = array<i32: 2>} : tensor<128x128xf16, #[[$ATTR_2]]> -> tensor<128x128xf16, #[[$ATTR_1]]>
// CHECK:             %[[VAL_358:.*]] = nvws.semaphore.acquire %[[VAL_98]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_359:.*]] = nvws.semaphore.buffer %[[VAL_98]], %[[VAL_358]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>
// CHECK:             %[[VAL_360:.*]] = ttg.local_load %[[VAL_359]] {ttg.partition = array<i32: 2>} : !ttg.memdesc<128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable> -> tensor<128x128xf16, #[[$ATTR_2]]>
// CHECK:             nvws.semaphore.release %[[VAL_97]], %[[VAL_358]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x128xf16, #[[$ATTR_9]], #[[$ATTR_11]], mutable>]>, !ttg.async.token
// CHECK:             %[[VAL_361:.*]] = ttg.convert_layout %[[VAL_360]] {ttg.partition = array<i32: 2>} : tensor<128x128xf16, #[[$ATTR_2]]> -> tensor<128x128xf16, #[[$ATTR_1]]>
// CHECK:             tt.descriptor_store %[[VAL_37]]{{\[}}%[[VAL_124]], %[[VAL_16]]], %[[VAL_357]] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>, tensor<128x128xf16, #[[$ATTR_1]]>
// CHECK:             tt.descriptor_store %[[VAL_38]]{{\[}}%[[VAL_125]], %[[VAL_16]]], %[[VAL_361]] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x128xf16, #[[$ATTR_9]]>>, tensor<128x128xf16, #[[$ATTR_1]]>
// CHECK:             %[[VAL_362:.*]] = arith.addi %[[VAL_111]], %[[VAL_23]] {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
// CHECK:             %[[VAL_363:.*]] = nvws.semaphore.acquire %[[VAL_68]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:             %[[VAL_364:.*]] = nvws.semaphore.acquire %[[VAL_85]] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x1xf32, #[[$ATTR_13]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf32, #[[$ATTR_12]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1x128x128xf16, #[[$ATTR_12]], #ttng.tensor_memory, mutable>]> -> !ttg.async.token
// CHECK:             scf.yield {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} %[[VAL_362]], %[[VAL_363]], %[[VAL_364]], %[[VAL_289]]#7, %[[VAL_289]]#8 : i32, !ttg.async.token, !ttg.async.token, !ttg.async.token, !ttg.async.token
// CHECK:           } {tt.data_partition_factor = 2 : i32, tt.merge_epilogue = true, tt.separate_epilogue_store = true, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>, ttg.partition.outputs = [array<i32: 0, 1, 2, 3, 4, 5>, array<i32: 1>, array<i32: 1>, array<i32: 0>, array<i32: 0>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32, 0 : i32, 0 : i32, 0 : i32], ttg.partition.types = ["correction", "gemm", "epilogue_store", "load", "computation", "computation"], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           tt.return
// CHECK:         }
  tt.func public @_attn_fwd_persist(%sm_scale: f32, %M: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %Z: i32, %H: i32 {tt.divisibility = 16 : i32}, %desc_q: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %desc_k: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %desc_v: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %desc_o: !tt.ptr<f16> {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %false = arith.constant false
    %true = arith.constant true
    %n_tile_num = arith.constant 64 : i32
    %c1_i32 = arith.constant 1 : i32
    %c16384_i32 = arith.constant 16384 : i32
    %c128_i32 = arith.constant 128 : i32
    %c128_i64 = arith.constant 128 : i64
    %c1_i64 = arith.constant 1 : i64
    %c0_i32 = arith.constant 0 : i32
    %c256_i32 = arith.constant 256 : i32
    %cst = arith.constant 1.44269502 : f32
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #linear>
    %cst_1 = arith.constant dense<0xFF800000> : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %cst_2 = arith.constant dense<1.000000e+00> : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %prog_id = tt.get_program_id x : i32
    %num_progs = tt.get_num_programs x : i32
    %total_tiles = arith.muli %Z, %n_tile_num : i32
    %total_tiles_3 = arith.muli %total_tiles, %H : i32
    %tiles_per_sm = arith.divsi %total_tiles_3, %num_progs : i32
    %0 = arith.remsi %total_tiles_3, %num_progs : i32
    %1 = arith.cmpi slt, %prog_id, %0 : i32
    %2 = scf.if %1 -> (i32) {
      %tiles_per_sm_19 = arith.addi %tiles_per_sm, %c1_i32 : i32
      scf.yield %tiles_per_sm_19 : i32
    } else {
      scf.yield %tiles_per_sm : i32
    }
    %desc_q_4 = arith.muli %Z, %H : i32
    %desc_q_5 = arith.muli %desc_q_4, %c16384_i32 : i32
    %desc_q_6 = tt.make_tensor_descriptor %desc_q, [%desc_q_5, %c128_i32], [%c128_i64, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #shared>>
    %desc_q_7 = tt.make_tensor_descriptor %desc_q, [%desc_q_5, %c128_i32], [%c128_i64, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #shared>>
    %desc_k_8 = tt.make_tensor_descriptor %desc_k, [%desc_q_5, %c128_i32], [%c128_i64, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #shared>>
    %desc_v_9 = tt.make_tensor_descriptor %desc_v, [%desc_q_5, %c128_i32], [%c128_i64, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #shared>>
    %desc_o_10 = tt.make_tensor_descriptor %desc_o, [%desc_q_5, %c128_i32], [%c128_i64, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #shared>>
    %desc_o_11 = tt.make_tensor_descriptor %desc_o, [%desc_q_5, %c128_i32], [%c128_i64, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<tensor<128x128xf16, #shared>>
    %offset_y = arith.muli %H, %c16384_i32 : i32
    %offs_m0 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked>
    %offs_m0_12 = tt.make_range {end = 256 : i32, start = 128 : i32} : tensor<128xi32, #blocked>
    %qk_scale = arith.mulf %sm_scale, %cst : f32
    %m_ij = tt.splat %qk_scale : f32 -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %m_ij_13 = tt.splat %qk_scale : f32 -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %qk = tt.splat %qk_scale : f32 -> tensor<128x128xf32, #linear>
    %qk_14 = tt.splat %qk_scale : f32 -> tensor<128x128xf32, #linear>
    %q0_0 = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %q0_1 = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %k = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %v = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %alpha = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 4 : i32, buffer.offset = 64 : i32} : () -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
    %alpha_15 = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 5 : i32, buffer.offset = 64 : i32} : () -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
    %offsetkv_y = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 4 : i32, buffer.offset = 66 : i32} : () -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
    %offsetkv_y_16 = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 4 : i32, buffer.offset = 65 : i32} : () -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
    %offsetkv_y_17 = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 5 : i32, buffer.offset = 66 : i32} : () -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
    %offsetkv_y_18 = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 5 : i32, buffer.offset = 65 : i32} : () -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
    %3 = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %4 = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %tile_idx = scf.for %_ = %c0_i32 to %2 step %c1_i32 iter_args(%tile_idx_19 = %prog_id) -> (i32)  : i32 {
      %pid = arith.remsi %tile_idx_19, %n_tile_num {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %off_hz = arith.divsi %tile_idx_19, %n_tile_num {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %off_z = arith.divsi %off_hz, %H {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %off_h = arith.remsi %off_hz, %H {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %offset_y_20 = arith.muli %off_z, %offset_y {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %offset_y_21 = arith.muli %off_h, %c16384_i32 {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %offset_y_22 = arith.addi %offset_y_20, %offset_y_21 {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %qo_offset_y = arith.muli %pid, %c256_i32 {ttg.partition = array<i32: 0, 2, 3>} : i32
      %qo_offset_y_23 = arith.addi %offset_y_22, %qo_offset_y {ttg.partition = array<i32: 2, 3>} : i32
      %5 = arith.addi %qo_offset_y_23, %c128_i32 {ttg.partition = array<i32: 2>} : i32
      %q0 = arith.addi %qo_offset_y_23, %c128_i32 {ttg.partition = array<i32: 3>} : i32
      %offs_m0_24 = tt.splat %qo_offset_y {ttg.partition = array<i32: 0, 2, 3>} : i32 -> tensor<128xi32, #blocked>
      %offs_m0_25 = tt.splat %qo_offset_y {ttg.partition = array<i32: 0, 2, 3>} : i32 -> tensor<128xi32, #blocked>
      %offs_m0_26 = arith.addi %offs_m0_24, %offs_m0 {ttg.partition = array<i32: 0>} : tensor<128xi32, #blocked>
      %offs_m0_27 = arith.addi %offs_m0_25, %offs_m0_12 {ttg.partition = array<i32: 0>} : tensor<128xi32, #blocked>
      nvws.descriptor_load %desc_q_6[%qo_offset_y_23, %c0_i32] 32768 %q0_0 {ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #shared>>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
      nvws.descriptor_load %desc_q_7[%q0, %c0_i32] 32768 %q0_1 {ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #shared>>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
      %qk_0, %qk_0_32 = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 4 : i32, buffer.offset = 0 : i32, ttg.partition = array<i32: 0, 1, 5>} : () -> (!ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>, !ttg.async.token)
      %qk_1, %qk_1_33 = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 5 : i32, buffer.offset = 0 : i32, ttg.partition = array<i32: 0, 1, 4>} : () -> (!ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>, !ttg.async.token)
      %acc_0, %acc_0_34 = ttng.tmem_alloc %cst_0 {buffer.copy = 1 : i32, buffer.id = 2 : i32, buffer.offset = 0 : i32, ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #linear>) -> (!ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>, !ttg.async.token)
      %acc_1, %acc_1_35 = ttng.tmem_alloc %cst_0 {buffer.copy = 1 : i32, buffer.id = 3 : i32, buffer.offset = 0 : i32, ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #linear>) -> (!ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>, !ttg.async.token)
      %offsetkv_y_40:9 = scf.for %offsetkv_y_88 = %c0_i32 to %c16384_i32 step %c128_i32 iter_args(%offset_y_89 = %offset_y_22, %arg12 = %cst_2, %arg13 = %cst_1, %qk_0_90 = %qk_0_32, %acc_91 = %acc_0_34, %arg16 = %cst_2, %arg17 = %cst_1, %qk_1_92 = %qk_1_33, %acc_93 = %acc_1_35) -> (i32, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, !ttg.async.token, !ttg.async.token, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, !ttg.async.token, !ttg.async.token)  : i32 {
        nvws.descriptor_load %desc_k_8[%offset_y_89, %c0_i32] 32768 %k {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #shared>>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
        %k_97 = ttg.memdesc_reinterpret %k {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable> -> !ttg.memdesc<128x128xf16, #shared, #smem>
        %k_98 = ttg.memdesc_trans %k_97 {loop.cluster = 1 : i32, loop.stage = 0 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #shared, #smem> -> !ttg.memdesc<128x128xf16, #shared1, #smem>
        nvws.descriptor_load %desc_v_9[%offset_y_89, %c0_i32] 32768 %v {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 3>} : !tt.tensordesc<tensor<128x128xf16, #shared>>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
        %qk_101 = ttng.tc_gen5_mma %q0_0, %k_98, %qk_0[%qk_0_90], %false, %true {loop.cluster = 1 : i32, loop.stage = 0 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable>, !ttg.memdesc<128x128xf16, #shared1, #smem>, !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>
        %qk_102 = ttng.tc_gen5_mma %q0_1, %k_98, %qk_1[%qk_1_92], %false, %true {loop.cluster = 3 : i32, loop.stage = 0 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable>, !ttg.memdesc<128x128xf16, #shared1, #smem>, !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>
        %qk_103, %qk_104 = ttng.tmem_load %qk_0[%qk_101] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear1>
        %qk_105 = ttg.convert_layout %qk_103 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #linear1> -> tensor<128x128xf32, #linear>
        %qk_106, %qk_107 = ttng.tmem_load %qk_1[%qk_102] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear1>
        %qk_108 = ttg.convert_layout %qk_106 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #linear1> -> tensor<128x128xf32, #linear>
        %m_ij_109 = "tt.reduce"(%qk_105) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
        ^bb0(%m_ij_176: f32, %m_ij_177: f32):
          %m_ij_178 = arith.maxnumf %m_ij_176, %m_ij_177 {ttg.partition = array<i32: 5>} : f32
          tt.reduce.return %m_ij_178 {ttg.partition = array<i32: 5>} : f32
        }) {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>, ttg.partition.outputs = [array<i32: 5>]} : (tensor<128x128xf32, #linear>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_110 = "tt.reduce"(%qk_108) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
        ^bb0(%m_ij_176: f32, %m_ij_177: f32):
          %m_ij_178 = arith.maxnumf %m_ij_176, %m_ij_177 {ttg.partition = array<i32: 4>} : f32
          tt.reduce.return %m_ij_178 {ttg.partition = array<i32: 4>} : f32
        }) {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>, ttg.partition.outputs = [array<i32: 4>]} : (tensor<128x128xf32, #linear>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_111 = arith.mulf %m_ij_109, %m_ij {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_112 = arith.mulf %m_ij_110, %m_ij_13 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_113 = arith.maxnumf %arg13, %m_ij_111 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_114 = arith.maxnumf %arg17, %m_ij_112 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %qk_115 = arith.mulf %qk_105, %qk {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #linear>
        %qk_116 = arith.mulf %qk_108, %qk_14 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #linear>
        %qk_117 = tt.expand_dims %m_ij_113 {axis = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %qk_118 = tt.expand_dims %m_ij_114 {axis = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %qk_119 = tt.broadcast %qk_117 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x1xf32, #linear> -> tensor<128x128xf32, #linear>
        %qk_120 = tt.broadcast %qk_118 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x1xf32, #linear> -> tensor<128x128xf32, #linear>
        %qk_121 = arith.subf %qk_115, %qk_119 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #linear>
        %qk_122 = arith.subf %qk_116, %qk_120 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #linear>
        %p = math.exp2 %qk_121 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #linear>
        %p_123 = math.exp2 %qk_122 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #linear>
        %alpha_124 = arith.subf %arg13, %m_ij_113 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %alpha_125 = arith.subf %arg17, %m_ij_114 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %alpha_126 = math.exp2 %alpha_124 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %alpha_127 = tt.expand_dims %alpha_126 {axis = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %alpha_128 = arith.constant {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} true
        ttng.tmem_store %alpha_127, %alpha, %alpha_128 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x1xf32, #linear> -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
        %alpha_129 = math.exp2 %alpha_125 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %alpha_130 = tt.expand_dims %alpha_129 {axis = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %alpha_131 = arith.constant {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} true
        ttng.tmem_store %alpha_130, %alpha_15, %alpha_131 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x1xf32, #linear> -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
        %l_ij = "tt.reduce"(%p) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
        ^bb0(%l_ij_176: f32, %l_ij_177: f32):
          %l_ij_178 = arith.addf %l_ij_176, %l_ij_177 {ttg.partition = array<i32: 5>} : f32
          tt.reduce.return %l_ij_178 {ttg.partition = array<i32: 5>} : f32
        }) {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 5>, ttg.partition.outputs = [array<i32: 5>]} : (tensor<128x128xf32, #linear>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %l_ij_132 = "tt.reduce"(%p_123) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
        ^bb0(%l_ij_176: f32, %l_ij_177: f32):
          %l_ij_178 = arith.addf %l_ij_176, %l_ij_177 {ttg.partition = array<i32: 4>} : f32
          tt.reduce.return %l_ij_178 {ttg.partition = array<i32: 4>} : f32
        }) {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>, ttg.partition.outputs = [array<i32: 4>]} : (tensor<128x128xf32, #linear>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %acc_133, %acc_134 = ttng.tmem_load %acc_0[%acc_91] {loop.cluster = 4 : i32, loop.stage = 0 : i32, tmem.end = array<i32: 8>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear1>
        %acc_135, %acc_136 = ttng.tmem_load %acc_1[%acc_93] {loop.cluster = 2 : i32, loop.stage = 1 : i32, tmem.end = array<i32: 11>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear1>
        %18 = tt.reshape %acc_133 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear1> -> tensor<128x2x64xf32, #linear2>
        %19 = tt.reshape %acc_135 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear1> -> tensor<128x2x64xf32, #linear2>
        %20 = tt.trans %18 {loop.cluster = 4 : i32, loop.stage = 0 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #linear2> -> tensor<128x64x2xf32, #linear3>
        %21 = tt.trans %19 {loop.cluster = 2 : i32, loop.stage = 1 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #linear2> -> tensor<128x64x2xf32, #linear3>
        %outLHS, %outRHS = tt.split %20 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #linear3> -> tensor<128x64xf32, #linear4>
        %outLHS_137, %outRHS_138 = tt.split %21 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #linear3> -> tensor<128x64xf32, #linear4>
        %alpha_139, %alpha_140 = ttng.tmem_load %alpha[] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x1xf32, #linear5>
        %alpha_141 = tt.reshape %alpha_139 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear5> -> tensor<128xf32, #linear6>
        %alpha_142 = ttg.convert_layout %alpha_141 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #linear6> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %acc0_143 = tt.expand_dims %alpha_142 {axis = 1 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %alpha_144, %alpha_145 = ttng.tmem_load %alpha_15[] {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x1xf32, #linear5>
        %alpha_146 = tt.reshape %alpha_144 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear5> -> tensor<128xf32, #linear6>
        %alpha_147 = ttg.convert_layout %alpha_146 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #linear6> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %acc0_148 = tt.expand_dims %alpha_147 {axis = 1 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %acc0_149 = ttg.convert_layout %acc0_143 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear> -> tensor<128x1xf32, #linear4>
        %acc0_150 = ttg.convert_layout %acc0_148 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear> -> tensor<128x1xf32, #linear4>
        %acc0_151 = tt.broadcast %acc0_149 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear4> -> tensor<128x64xf32, #linear4>
        %acc0_152 = tt.broadcast %acc0_150 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear4> -> tensor<128x64xf32, #linear4>
        %acc0_153 = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 4 : i32, loop.stage = 0 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %outLHS, %acc0_151 : tensor<128x64xf32, #linear4>, tensor<128x64xf32, #linear4> -> tensor<128x64xf32, #linear4>
        %acc0_154 = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 2 : i32, loop.stage = 1 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %outLHS_137, %acc0_152 : tensor<128x64xf32, #linear4>, tensor<128x64xf32, #linear4> -> tensor<128x64xf32, #linear4>
        %acc1 = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 4 : i32, loop.stage = 0 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %outRHS, %acc0_151 : tensor<128x64xf32, #linear4>, tensor<128x64xf32, #linear4> -> tensor<128x64xf32, #linear4>
        %acc1_155 = tt.elementwise_inline_asm "\0A        {\0A            .reg .b64 ra, rb, rc;\0A            mov.b64 ra, { $2, $3 };\0A            mov.b64 rb, { $4, $5 };\0A            mul.f32x2 rc, ra, rb;\0A            mov.b64 { $0, $1 }, rc;\0A        }\0A        " {constraints = "=r,=r,r,r,r,r", loop.cluster = 2 : i32, loop.stage = 1 : i32, packed_element = 2 : i32, pure = true, ttg.partition = array<i32: 0>} %outRHS_138, %acc0_152 : tensor<128x64xf32, #linear4>, tensor<128x64xf32, #linear4> -> tensor<128x64xf32, #linear4>
        %acc_156 = tt.join %acc0_153, %acc1 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x64xf32, #linear4> -> tensor<128x64x2xf32, #linear3>
        %acc_157 = tt.join %acc0_154, %acc1_155 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x64xf32, #linear4> -> tensor<128x64x2xf32, #linear3>
        %acc_158 = tt.trans %acc_156 {loop.cluster = 4 : i32, loop.stage = 0 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #linear3> -> tensor<128x2x64xf32, #linear2>
        %acc_159 = tt.trans %acc_157 {loop.cluster = 2 : i32, loop.stage = 1 : i32, order = array<i32: 0, 2, 1>, ttg.partition = array<i32: 0>} : tensor<128x64x2xf32, #linear3> -> tensor<128x2x64xf32, #linear2>
        %acc_160 = tt.reshape %acc_158 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #linear2> -> tensor<128x128xf32, #linear>
        %acc_161 = tt.reshape %acc_159 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128x2x64xf32, #linear2> -> tensor<128x128xf32, #linear>
        %p_162 = arith.truncf %p {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : tensor<128x128xf32, #linear> to tensor<128x128xf16, #linear>
        %p_163 = arith.truncf %p_123 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128x128xf32, #linear> to tensor<128x128xf16, #linear>
        %acc_164 = ttng.tmem_alloc %p_162 {buffer.copy = 1 : i32, buffer.id = 4 : i32, buffer.offset = 0 : i32, loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 5>} : (tensor<128x128xf16, #linear>) -> !ttg.memdesc<128x128xf16, #tmem1, #ttng.tensor_memory>
        %acc_165 = ttng.tmem_alloc %p_163 {buffer.copy = 1 : i32, buffer.id = 5 : i32, buffer.offset = 0 : i32, loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : (tensor<128x128xf16, #linear>) -> !ttg.memdesc<128x128xf16, #tmem1, #ttng.tensor_memory>
        %acc_166 = ttng.tmem_store %acc_160, %acc_0[%acc_134], %true {loop.cluster = 4 : i32, loop.stage = 0 : i32, tmem.start = array<i32: 9>, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> -> !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>
        %acc_167 = ttng.tmem_store %acc_161, %acc_1[%acc_136], %true {loop.cluster = 2 : i32, loop.stage = 1 : i32, tmem.start = array<i32: 12>, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> -> !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>
        %acc_170 = ttng.tc_gen5_mma %acc_164, %v, %acc_0[%acc_166], %true, %true {loop.cluster = 4 : i32, loop.stage = 0 : i32, tmem.end = array<i32: 9>, tmem.start = array<i32: 8, 10>, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #tmem1, #ttng.tensor_memory>, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>, !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>
        %acc_171 = ttng.tc_gen5_mma %acc_165, %v, %acc_1[%acc_167], %true, %true {loop.cluster = 2 : i32, loop.stage = 1 : i32, tmem.end = array<i32: 12>, tmem.start = array<i32: 11, 13>, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #tmem1, #ttng.tensor_memory>, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>, !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable>
        %l_i0 = arith.mulf %arg12, %alpha_126 {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %l_i0_172 = arith.mulf %arg16, %alpha_129 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %l_i0_173 = arith.addf %l_i0, %l_ij {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %l_i0_174 = arith.addf %l_i0_172, %l_ij_132 {loop.cluster = 2 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %offsetkv_y_175 = arith.addi %offset_y_89, %c128_i32 {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 3>} : i32
        scf.yield {ttg.partition = array<i32: 0, 1, 3, 4, 5>} %offsetkv_y_175, %l_i0_173, %m_ij_113, %qk_104, %acc_170, %l_i0_174, %m_ij_114, %qk_107, %acc_171 : i32, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, !ttg.async.token, !ttg.async.token, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, !ttg.async.token, !ttg.async.token
      } {tt.data_partition_factor = 2 : i32, tt.merge_epilogue = true, tt.scheduled_max_stage = 1 : i32, tt.separate_epilogue_store = true, ttg.partition = array<i32: 0, 1, 3, 4, 5>, ttg.partition.outputs = [array<i32: 3>, array<i32: 5>, array<i32: 5>, array<i32: 1>, array<i32: 0>, array<i32: 4>, array<i32: 4>, array<i32: 1>, array<i32: 0>]}
      %offsetkv_y_41 = tt.expand_dims %offsetkv_y_40#6 {axis = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
      %offsetkv_y_42 = arith.constant {ttg.partition = array<i32: 4>} true
      ttng.tmem_store %offsetkv_y_41, %offsetkv_y_18, %offsetkv_y_42 {ttg.partition = array<i32: 4>} : tensor<128x1xf32, #linear> -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
      %offsetkv_y_43 = tt.expand_dims %offsetkv_y_40#5 {axis = 1 : i32, ttg.partition = array<i32: 4>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
      %offsetkv_y_44 = arith.constant {ttg.partition = array<i32: 4>} true
      ttng.tmem_store %offsetkv_y_43, %offsetkv_y_17, %offsetkv_y_44 {ttg.partition = array<i32: 4>} : tensor<128x1xf32, #linear> -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
      %offsetkv_y_45 = tt.expand_dims %offsetkv_y_40#2 {axis = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
      %offsetkv_y_46 = arith.constant {ttg.partition = array<i32: 5>} true
      ttng.tmem_store %offsetkv_y_45, %offsetkv_y_16, %offsetkv_y_46 {ttg.partition = array<i32: 5>} : tensor<128x1xf32, #linear> -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
      %offsetkv_y_47 = tt.expand_dims %offsetkv_y_40#1 {axis = 1 : i32, ttg.partition = array<i32: 5>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
      %offsetkv_y_48 = arith.constant {ttg.partition = array<i32: 5>} true
      ttng.tmem_store %offsetkv_y_47, %offsetkv_y, %offsetkv_y_48 {ttg.partition = array<i32: 5>} : tensor<128x1xf32, #linear> -> !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable>
      %offsetkv_y_49, %offsetkv_y_50 = ttng.tmem_load %offsetkv_y[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x1xf32, #linear5>
      %offsetkv_y_51 = tt.reshape %offsetkv_y_49 {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear5> -> tensor<128xf32, #linear6>
      %offsetkv_y_52 = ttg.convert_layout %offsetkv_y_51 {ttg.partition = array<i32: 0>} : tensor<128xf32, #linear6> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %m_i0 = math.log2 %offsetkv_y_52 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %offsetkv_y_53, %offsetkv_y_54 = ttng.tmem_load %offsetkv_y_17[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x1xf32, #linear5>
      %offsetkv_y_55 = tt.reshape %offsetkv_y_53 {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear5> -> tensor<128xf32, #linear6>
      %offsetkv_y_56 = ttg.convert_layout %offsetkv_y_55 {ttg.partition = array<i32: 0>} : tensor<128xf32, #linear6> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %m_i0_57 = math.log2 %offsetkv_y_56 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %offsetkv_y_58, %offsetkv_y_59 = ttng.tmem_load %offsetkv_y_16[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x1xf32, #linear5>
      %offsetkv_y_60 = tt.reshape %offsetkv_y_58 {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear5> -> tensor<128xf32, #linear6>
      %offsetkv_y_61 = ttg.convert_layout %offsetkv_y_60 {ttg.partition = array<i32: 0>} : tensor<128xf32, #linear6> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %m_i0_62 = arith.addf %offsetkv_y_61, %m_i0 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %offsetkv_y_63, %offsetkv_y_64 = ttng.tmem_load %offsetkv_y_18[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x1xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x1xf32, #linear5>
      %offsetkv_y_65 = tt.reshape %offsetkv_y_63 {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear5> -> tensor<128xf32, #linear6>
      %offsetkv_y_66 = ttg.convert_layout %offsetkv_y_65 {ttg.partition = array<i32: 0>} : tensor<128xf32, #linear6> -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %m_i0_67 = arith.addf %offsetkv_y_66, %m_i0_57 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
      %acc0 = tt.expand_dims %offsetkv_y_52 {axis = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
      %acc0_68 = tt.expand_dims %offsetkv_y_56 {axis = 1 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
      %acc0_69 = tt.broadcast %acc0 {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear> -> tensor<128x128xf32, #linear>
      %acc0_70 = tt.broadcast %acc0_68 {ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear> -> tensor<128x128xf32, #linear>
      %acc, %acc_71 = ttng.tmem_load %acc_0[%offsetkv_y_40#4] {tmem.end = array<i32: 10>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear1>
      %acc_72 = ttg.convert_layout %acc {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear1> -> tensor<128x128xf32, #linear>
      %acc_73, %acc_74 = ttng.tmem_load %acc_1[%offsetkv_y_40#8] {tmem.end = array<i32: 13>, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem1, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear1>
      %acc_75 = ttg.convert_layout %acc_73 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear1> -> tensor<128x128xf32, #linear>
      %acc0_76 = arith.divf %acc_72, %acc0_69 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear>
      %acc0_77 = arith.divf %acc_75, %acc0_70 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear>
      %m_ptrs0 = arith.muli %off_hz, %c16384_i32 {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      %m_ptrs0_78 = tt.addptr %M, %m_ptrs0 {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : !tt.ptr<f32>, i32
      %m_ptrs0_79 = tt.splat %m_ptrs0_78 {ttg.partition = array<i32: 0>} : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>, #blocked>
      %m_ptrs0_80 = tt.splat %m_ptrs0_78 {ttg.partition = array<i32: 0>} : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>, #blocked>
      %m_ptrs0_81 = tt.addptr %m_ptrs0_79, %offs_m0_26 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #blocked>, tensor<128xi32, #blocked>
      %m_ptrs0_82 = tt.addptr %m_ptrs0_80, %offs_m0_27 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #blocked>, tensor<128xi32, #blocked>
      %6 = ttg.convert_layout %m_i0_62 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128xf32, #blocked>
      %7 = ttg.convert_layout %m_i0_67 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128xf32, #blocked>
      tt.store %m_ptrs0_81, %6 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #blocked>
      tt.store %m_ptrs0_82, %7 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f32>, #blocked>
      %8 = arith.truncf %acc0_76 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> to tensor<128x128xf16, #linear>
      ttg.local_store %8, %3 {ttg.partition = array<i32: 0>} : tensor<128x128xf16, #linear> -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
      %10 = arith.truncf %acc0_77 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> to tensor<128x128xf16, #linear>
      ttg.local_store %10, %4 {ttg.partition = array<i32: 0>} : tensor<128x128xf16, #linear> -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
      %13 = ttg.local_load %3 {ttg.partition = array<i32: 2>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable> -> tensor<128x128xf16, #linear>
      %14 = ttg.convert_layout %13 {ttg.partition = array<i32: 2>} : tensor<128x128xf16, #linear> -> tensor<128x128xf16, #blocked1>
      %16 = ttg.local_load %4 {ttg.partition = array<i32: 2>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable> -> tensor<128x128xf16, #linear>
      %17 = ttg.convert_layout %16 {ttg.partition = array<i32: 2>} : tensor<128x128xf16, #linear> -> tensor<128x128xf16, #blocked1>
      tt.descriptor_store %desc_o_10[%qo_offset_y_23, %c0_i32], %14 {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x128xf16, #shared>>, tensor<128x128xf16, #blocked1>
      tt.descriptor_store %desc_o_11[%5, %c0_i32], %17 {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x128xf16, #shared>>, tensor<128x128xf16, #blocked1>
      %tile_idx_87 = arith.addi %tile_idx_19, %num_progs {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} : i32
      scf.yield {ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>} %tile_idx_87 : i32
    } {tt.data_partition_factor = 2 : i32, tt.merge_epilogue = true, tt.separate_epilogue_store = true, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2, 3, 4, 5>, ttg.partition.outputs = [array<i32: 0, 1, 2, 3, 4, 5>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32, 0 : i32, 0 : i32, 0 : i32], ttg.partition.types = ["correction", "gemm", "epilogue_store", "load", "computation", "computation"], ttg.warp_specialize.tag = 0 : i32}
    tt.return
  }
}
