// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK: #[[$ATTR_0:.+]] = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
// CHECK: #[[$ATTR_1:.+]] = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
// CHECK: #[[$ATTR_2:.+]] = #ttg.shared_memory
// RUN: triton-opt %s -split-input-file --allow-unregistered-dialect --nvws-lower-aref-to-semaphore | FileCheck %s --implicit-check-not=nvws.aref.


#blocked = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#shared = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#smem = #ttg.shared_memory
!ty = tensor<1xi32, #blocked>

module attributes {"ttg.num-warps" = 4 : i32} {
// CHECK-LABEL:   tt.func @basic(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32) {
// CHECK:           %[[VAL_3:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>
// CHECK:           %[[VAL_4:.*]] = nvws.semaphore.create %[[VAL_3]] true : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_3]] false : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>
// CHECK:           scf.for %[[VAL_6:.*]] = %[[VAL_0]] to %[[VAL_1]] step %[[VAL_2]]  : i32 {
// CHECK:             %[[VAL_7:.*]] = "producer"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #[[$ATTR_0]]>
// CHECK:             %[[VAL_8:.*]] = nvws.semaphore.acquire %[[VAL_4]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_9:.*]] = nvws.semaphore.buffer %[[VAL_4]], %[[VAL_8]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1>
// CHECK:             %[[VAL_10:.*]] = nvws.semaphore.buffer %[[VAL_4]], %[[VAL_8]] : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1>
// CHECK:             ttg.local_store %[[VAL_7]], %[[VAL_10]] {ttg.partition = array<i32: 0>} : tensor<1xi32, #[[$ATTR_0]]> -> !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1>
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_8]] [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_11:.*]] = nvws.semaphore.acquire %[[VAL_5]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_12:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_11]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1>
// CHECK:             %[[VAL_13:.*]] = ttg.local_load %[[VAL_12]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_0]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_11]] [#nvws.async_op<none>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token
// CHECK:             "consumer0"(%[[VAL_13]]) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #[[$ATTR_0]]>) -> ()
// CHECK:             %[[VAL_14:.*]] = nvws.semaphore.acquire %[[VAL_5]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_15:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_14]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1>
// CHECK:             %[[VAL_16:.*]] = ttg.local_load %[[VAL_15]] {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_0]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_14]] [#nvws.async_op<none>] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>],>, !ttg.async.token
// CHECK:             "consumer1"(%[[VAL_16]]) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #[[$ATTR_0]]>) -> ()
// CHECK:           }
// CHECK:           ttg.local_dealloc %[[VAL_3]] : !ttg.memdesc<1x1xi32, #[[$ATTR_1]], #[[$ATTR_2]], mutable>
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_3:.+]] = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
// CHECK: #[[$ATTR_4:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_5:.+]] = #ttg.shared_memory
  tt.func @basic(%lb: i32, %ub: i32, %step: i32) {
    %c0_i32 = arith.constant 0 : i32
    %buf = ttg.local_alloc : () -> !ttg.memdesc<1x1xi32, #shared, #smem, mutable>
    %aref = nvws.aref.create %buf : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>
    scf.for %i = %lb to %ub step %step : i32 {
      %v = "producer"() {ttg.partition = array<i32: 0>} : () -> !ty
      %pb, %ptok = nvws.aref.put.enter %aref {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %pb_from_tok = nvws.aref.buffer %aref, %ptok : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>
      ttg.local_store %v, %pb_from_tok {ttg.partition = array<i32: 0>} : !ty -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>
      nvws.aref.put.exit %aref, %ptok [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token

      %gb0, %gtok0 = nvws.aref.get.enter %aref {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %x = ttg.local_load %gb0 {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> !ty
      nvws.aref.get.exit %aref, %gtok0 [#nvws.async_op<none>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "consumer0"(%x) {ttg.partition = array<i32: 1>} : (!ty) -> ()

      %gb1, %gtok1 = nvws.aref.get.enter %aref {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %y = ttg.local_load %gb1 {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> !ty
      nvws.aref.get.exit %aref, %gtok1 [#nvws.async_op<none>] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "consumer1"(%y) {ttg.partition = array<i32: 2>} : (!ty) -> ()
    }
    ttg.local_dealloc %buf : !ttg.memdesc<1x1xi32, #shared, #smem, mutable>
    tt.return
  }
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory

module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func @tma_preserved(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_4]]>>, %[[VAL_1:.*]]: i32) {
// CHECK:           %[[VAL_2:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_3:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>
// CHECK:           %[[VAL_4:.*]] = nvws.semaphore.create %[[VAL_3]] true : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_3]] false : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3>
// CHECK:           %[[VAL_6:.*]] = nvws.semaphore.acquire %[[VAL_4]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3> -> !ttg.async.token
// CHECK:           %[[VAL_7:.*]] = nvws.semaphore.buffer %[[VAL_4]], %[[VAL_6]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>
// CHECK:           nvws.descriptor_load %[[VAL_0]]{{\[}}%[[VAL_1]], %[[VAL_2]]] 16384 %[[VAL_7]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_4]]>>, i32, i32, !ttg.memdesc<128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>
// CHECK:           nvws.semaphore.release %[[VAL_5]], %[[VAL_6]] [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3>, !ttg.async.token
// CHECK:           %[[VAL_8:.*]] = nvws.semaphore.acquire %[[VAL_5]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3> -> !ttg.async.token
// CHECK:           %[[VAL_9:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_8]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>
// CHECK:           %[[VAL_10:.*]] = ttg.local_load %[[VAL_9]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable> -> tensor<128x64xf16, #[[$ATTR_3]]>
// CHECK:           nvws.semaphore.release %[[VAL_4]], %[[VAL_8]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>], 3>, !ttg.async.token
// CHECK:           "use"(%[[VAL_10]]) : (tensor<128x64xf16, #[[$ATTR_3]]>) -> ()
// CHECK:           ttg.local_dealloc %[[VAL_3]] : !ttg.memdesc<3x128x64xf16, #[[$ATTR_4]], #[[$ATTR_5]], mutable>
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_6:.+]] = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
// CHECK: #[[$ATTR_7:.+]] = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
// CHECK: #[[$ATTR_8:.+]] = #ttg.shared_memory
  tt.func @tma_preserved(%desc: !tt.tensordesc<tensor<128x64xf16, #shared>>, %idx: i32) {
    %c0_i32 = arith.constant 0 : i32
    %buf = ttg.local_alloc : () -> !ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>
    %aref = nvws.aref.create %buf : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>

    %pb, %ptok = nvws.aref.put.enter %aref {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>, !ttg.async.token
    nvws.descriptor_load %desc[%idx, %c0_i32] 16384 %pb {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>>, i32, i32, !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
    nvws.aref.put.exit %aref, %ptok [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token

    %gb, %gtok = nvws.aref.get.enter %aref {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>, !ttg.async.token
    %v = ttg.local_load %gb {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem, mutable> -> tensor<128x64xf16, #blocked>
    nvws.aref.get.exit %aref, %gtok [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
    "use"(%v) : (tensor<128x64xf16, #blocked>) -> ()

    ttg.local_dealloc %buf : !ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>
    tt.return
  }
}









// -----

#blocked = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#shared = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#smem = #ttg.shared_memory
module attributes {"ttg.num-warps" = 4 : i32} {

// CHECK-LABEL:   tt.func @two_consumers(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32) {
// CHECK:           %[[VAL_3:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>
// CHECK:           %[[VAL_4:.*]] = nvws.semaphore.create %[[VAL_3]] true : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_3]] false : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>
// CHECK:           scf.for %[[VAL_6:.*]] = %[[VAL_0]] to %[[VAL_1]] step %[[VAL_2]]  : i32 {
// CHECK:             %[[VAL_7:.*]] = "op_a"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             %[[VAL_8:.*]] = nvws.semaphore.acquire %[[VAL_4]] {loop.cluster = 1 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_9:.*]] = nvws.semaphore.buffer %[[VAL_4]], %[[VAL_8]] {loop.cluster = 1 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             ttg.local_store %[[VAL_7]], %[[VAL_9]] {ttg.partition = array<i32: 0>} : tensor<1xi32, #[[$ATTR_6]]> -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_8]] [#nvws.async_op<none>] {loop.cluster = 1 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_10:.*]] = nvws.semaphore.acquire %[[VAL_5]] {loop.cluster = 2 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_11:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_10]] {loop.cluster = 2 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_12:.*]] = ttg.local_load %[[VAL_11]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_10]] [#nvws.async_op<none>] {loop.cluster = 2 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             "op_b"(%[[VAL_12]]) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             %[[VAL_13:.*]] = nvws.semaphore.acquire %[[VAL_5]] {loop.cluster = 3 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_14:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_13]] {loop.cluster = 3 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_15:.*]] = ttg.local_load %[[VAL_14]] {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_13]] [#nvws.async_op<none>] {loop.cluster = 3 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             "op_c"(%[[VAL_15]]) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             "op_d"(%[[VAL_15]]) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:           } {ttg.partition = array<i32: 0, 1, 2>, ttg.partition.stages = [0 : i32, 2 : i32, 2 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           ttg.local_dealloc %[[VAL_3]] : !ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>
// CHECK:           tt.return
// CHECK:         }
  tt.func @two_consumers(%arg0: i32, %arg1: i32, %arg2: i32) {
    %c0_i32 = arith.constant 0 : i32
    %c2_i32 = arith.constant 2 : i32
    %c1_i32 = arith.constant 1 : i32
    %c3_i32 = arith.constant 3 : i32
    %0 = ttg.local_alloc : () -> !ttg.memdesc<3x1xi32, #shared, #smem, mutable>
    %1 = nvws.aref.create %0 : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>
    scf.for %arg3 = %arg0 to %arg1 step %arg2 : i32 {
      %3 = "op_a"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #blocked>
      %buffers, %token = nvws.aref.put.enter %1[%c0_i32, %c0_i32] {loop.cluster = 1 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      ttg.local_store %3, %buffers {ttg.partition = array<i32: 0>} : tensor<1xi32, #blocked> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>
      nvws.aref.put.exit %1[%c0_i32], %token [#nvws.async_op<none>] {loop.cluster = 1 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_0, %token_1 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {loop.cluster = 2 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %14 = ttg.local_load %buffers_0 {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_1 [#nvws.async_op<none>] {loop.cluster = 2 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_b"(%14) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #blocked>) -> ()
      %buffers_2, %token_3 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {loop.cluster = 3 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %20 = ttg.local_load %buffers_2 {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_3 [#nvws.async_op<none>] {loop.cluster = 3 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_c"(%20) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #blocked>) -> ()
      "op_d"(%20) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #blocked>) -> ()
    } {ttg.partition.stages = [0 : i32, 2 : i32, 2 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2>}
    ttg.local_dealloc %0 : !ttg.memdesc<3x1xi32, #shared, #smem, mutable>
    tt.return
  }

// CHECK-LABEL:   tt.func @three_consumers(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32) {
// CHECK:           %[[VAL_3:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>
// CHECK:           %[[VAL_4:.*]] = nvws.semaphore.create %[[VAL_3]] true : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_3]] false : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>
// CHECK:           scf.for %[[VAL_6:.*]] = %[[VAL_0]] to %[[VAL_1]] step %[[VAL_2]]  : i32 {
// CHECK:             %[[VAL_7:.*]] = "op_a"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             %[[VAL_8:.*]] = nvws.semaphore.acquire %[[VAL_4]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_9:.*]] = nvws.semaphore.buffer %[[VAL_4]], %[[VAL_8]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             ttg.local_store %[[VAL_7]], %[[VAL_9]] {ttg.partition = array<i32: 0>} : tensor<1xi32, #[[$ATTR_6]]> -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_8]] [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_10:.*]] = nvws.semaphore.acquire %[[VAL_5]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_11:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_10]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_12:.*]] = ttg.local_load %[[VAL_11]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_10]] [#nvws.async_op<none>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             "op_b"(%[[VAL_12]]) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             %[[VAL_13:.*]] = nvws.semaphore.acquire %[[VAL_5]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_14:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_13]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_15:.*]] = ttg.local_load %[[VAL_14]] {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_13]] [#nvws.async_op<none>] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             "op_c"(%[[VAL_15]]) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             "op_d"(%[[VAL_15]]) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             %[[VAL_16:.*]] = nvws.semaphore.acquire %[[VAL_5]] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_17:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_16]] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_18:.*]] = ttg.local_load %[[VAL_17]] {ttg.partition = array<i32: 3>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_4]], %[[VAL_16]] [#nvws.async_op<none>] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>], 3>, !ttg.async.token
// CHECK:             "op_e"(%[[VAL_18]]) {ttg.partition = array<i32: 3>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             "op_f"(%[[VAL_18]]) {ttg.partition = array<i32: 3>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:           } {ttg.partition = array<i32: 0, 1, 2, 3>, ttg.partition.stages = [0 : i32, 2 : i32, 2 : i32, 3 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           ttg.local_dealloc %[[VAL_3]] : !ttg.memdesc<3x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>
// CHECK:           tt.return
// CHECK:         }
  tt.func @three_consumers(%arg0: i32, %arg1: i32, %arg2: i32) {
    %c0_i32 = arith.constant 0 : i32
    %c2_i32 = arith.constant 2 : i32
    %c1_i32 = arith.constant 1 : i32
    %c3_i32 = arith.constant 3 : i32
    %0 = ttg.local_alloc : () -> !ttg.memdesc<3x1xi32, #shared, #smem, mutable>
    %1 = nvws.aref.create %0 : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>
    scf.for %arg3 = %arg0 to %arg1 step %arg2 : i32 {
      %3 = "op_a"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #blocked>
      %buffers, %token = nvws.aref.put.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      ttg.local_store %3, %buffers {ttg.partition = array<i32: 0>} : tensor<1xi32, #blocked> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>
      nvws.aref.put.exit %1[%c0_i32], %token [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_0, %token_1 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %14 = ttg.local_load %buffers_0 {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_1 [#nvws.async_op<none>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_b"(%14) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #blocked>) -> ()
      %buffers_2, %token_3 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %20 = ttg.local_load %buffers_2 {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_3 [#nvws.async_op<none>] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_c"(%20) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #blocked>) -> ()
      "op_d"(%20) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #blocked>) -> ()
      %buffers_4, %token_5 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %26 = ttg.local_load %buffers_4 {ttg.partition = array<i32: 3>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_5 [#nvws.async_op<none>] {ttg.partition = array<i32: 3>} : <[!ttg.memdesc<3x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_e"(%26) {ttg.partition = array<i32: 3>} : (tensor<1xi32, #blocked>) -> ()
      "op_f"(%26) {ttg.partition = array<i32: 3>} : (tensor<1xi32, #blocked>) -> ()
    } {ttg.partition.stages = [0 : i32, 2 : i32, 2 : i32, 3 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2, 3>}
    ttg.local_dealloc %0 : !ttg.memdesc<3x1xi32, #shared, #smem, mutable>
    tt.return
  }


// CHECK-LABEL:   tt.func @reuse_argument(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32) {
// CHECK:           %[[VAL_3:.*]] = arith.constant dense<1> : tensor<1xi32, #[[$ATTR_6]]>
// CHECK:           %[[VAL_4:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_4]] true : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>
// CHECK:           %[[VAL_6:.*]] = nvws.semaphore.create %[[VAL_4]] false : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>
// CHECK:           %[[VAL_7:.*]] = scf.for %[[VAL_8:.*]] = %[[VAL_0]] to %[[VAL_1]] step %[[VAL_2]] iter_args(%[[VAL_9:.*]] = %[[VAL_3]]) -> (tensor<1xi32, #[[$ATTR_6]]>)  : i32 {
// CHECK:             %[[VAL_10:.*]] = nvws.semaphore.acquire %[[VAL_5]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_11:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_10]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             ttg.local_store %[[VAL_9]], %[[VAL_11]] {ttg.partition = array<i32: 0>} : tensor<1xi32, #[[$ATTR_6]]> -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             nvws.semaphore.release %[[VAL_6]], %[[VAL_10]] [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_12:.*]] = "op_a"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             %[[VAL_13:.*]] = nvws.semaphore.acquire %[[VAL_6]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_14:.*]] = nvws.semaphore.buffer %[[VAL_6]], %[[VAL_13]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_15:.*]] = ttg.local_load %[[VAL_14]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_13]] [#nvws.async_op<none>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>, !ttg.async.token
// CHECK:             "op_d"(%[[VAL_15]]) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             %[[VAL_16:.*]] = nvws.semaphore.acquire %[[VAL_6]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_17:.*]] = nvws.semaphore.buffer %[[VAL_6]], %[[VAL_16]] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>, !ttg.async.token -> !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1>
// CHECK:             %[[VAL_18:.*]] = ttg.local_load %[[VAL_17]] {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable, 1x1> -> tensor<1xi32, #[[$ATTR_6]]>
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_16]] [#nvws.async_op<none>] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>],>, !ttg.async.token
// CHECK:             "op_d"(%[[VAL_18]]) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #[[$ATTR_6]]>) -> ()
// CHECK:             scf.yield %[[VAL_12]] : tensor<1xi32, #[[$ATTR_6]]>
// CHECK:           } {ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 0>], ttg.partition.stages = [1 : i32, 0 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           ttg.local_dealloc %[[VAL_4]] : !ttg.memdesc<1x1xi32, #[[$ATTR_7]], #[[$ATTR_8]], mutable>
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_9:.+]] = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
// CHECK: #[[$ATTR_10:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_11:.+]] = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
// CHECK: #[[$ATTR_12:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
// CHECK: #[[$ATTR_13:.+]] = #ttg.shared_memory
// CHECK: #[[$ATTR_14:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
  tt.func @reuse_argument(%arg0: i32, %arg1: i32, %arg2: i32) {
    %true = arith.constant true
    %cst = arith.constant dense<1> : tensor<1xi32, #blocked>
    %cst_0 = arith.constant dense<0> : tensor<1xi32, #blocked>
    %c0_i32 = arith.constant 0 : i32
    %c1_i32 = arith.constant 1 : i32
    %0 = ttg.local_alloc : () -> !ttg.memdesc<1x1xi32, #shared, #smem, mutable>
    %1 = nvws.aref.create %0 : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>
    scf.for %arg3 = %arg0 to %arg1 step %arg2 iter_args(%arg5 = %cst) -> (tensor<1xi32, #blocked>)  : i32 {
      %buffers, %token = nvws.aref.put.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      ttg.local_store %arg5, %buffers {ttg.partition = array<i32: 0>} : tensor<1xi32, #blocked> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>
      nvws.aref.put.exit %1[%c0_i32], %token [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      %5 = "op_a"() {ttg.partition = array<i32: 0>} : () -> tensor<1xi32, #blocked>

      %buffers_1, %token_2 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %8 = ttg.local_load %buffers_1 {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_2 [#nvws.async_op<none>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_d"(%8) {ttg.partition = array<i32: 1>} : (tensor<1xi32, #blocked>) -> ()

      %buffers_3, %token_4 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]> -> !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1>, !ttg.async.token
      %11 = ttg.local_load %buffers_3 {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #shared, #smem, mutable, 1x1> -> tensor<1xi32, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_4 [#nvws.async_op<none>] {ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x1xi32, #shared, #smem, mutable>]>, !ttg.async.token
      "op_d"(%11) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #blocked>) -> ()
      scf.yield %5 : tensor<1xi32, #blocked>
    } {ttg.partition.stages = [1 : i32, 0 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 0>]}
    ttg.local_dealloc %0 : !ttg.memdesc<1x1xi32, #shared, #smem, mutable>
    tt.return
  }
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#shared2 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func @warp_specialize_tma_matmul(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_10]]>>, %[[VAL_4:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_10]]>>) {
// CHECK:           %[[VAL_5:.*]] = ub.poison : !ttg.async.token
// CHECK:           %[[VAL_6:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #[[$ATTR_9]]>
// CHECK:           %[[VAL_7:.*]] = arith.constant 64 : i32
// CHECK:           %[[VAL_8:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_9:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_10:.*]] = arith.constant true
// CHECK:           %[[VAL_11:.*]], %[[VAL_12:.*]] = ttng.tmem_alloc : () -> (!ttg.memdesc<1x128x128xf32, #[[$ATTR_14]], #ttng.tensor_memory, mutable>, !ttg.async.token)
// CHECK:           %[[VAL_13:.*]] = ttg.memdesc_index %[[VAL_11]]{{\[}}%[[VAL_9]]] : !ttg.memdesc<1x128x128xf32, #[[$ATTR_14]], #ttng.tensor_memory, mutable> -> !ttg.memdesc<128x128xf32, #[[$ATTR_14]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_14:.*]] = ttng.tmem_store %[[VAL_6]], %[[VAL_13]]{{\[}}%[[VAL_12]]], %[[VAL_10]] : tensor<128x128xf32, #[[$ATTR_9]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_14]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_15:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>
// CHECK:           %[[VAL_16:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>
// CHECK:           %[[VAL_17:.*]] = nvws.semaphore.create %[[VAL_15]], %[[VAL_16]] true : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3>
// CHECK:           %[[VAL_18:.*]] = nvws.semaphore.create %[[VAL_15]], %[[VAL_16]] false : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3>
// CHECK:           %[[VAL_19:.*]] = arith.subi %[[VAL_0]], %[[VAL_8]] : i32
// CHECK:           %[[VAL_20:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64, #[[$ATTR_11]], #[[$ATTR_13]], mutable>
// CHECK:           %[[VAL_21:.*]] = ttg.memdesc_index %[[VAL_20]]{{\[}}%[[VAL_9]]] : !ttg.memdesc<1x1xi64, #[[$ATTR_11]], #[[$ATTR_13]], mutable> -> !ttg.memdesc<1xi64, #[[$ATTR_11]], #[[$ATTR_13]], mutable>
// CHECK:           ttng.init_barrier %[[VAL_21]], 1 : !ttg.memdesc<1xi64, #[[$ATTR_11]], #[[$ATTR_13]], mutable>
// CHECK:           %[[VAL_22:.*]] = scf.for %[[VAL_23:.*]] = %[[VAL_9]] to %[[VAL_0]] step %[[VAL_8]] iter_args(%[[VAL_24:.*]] = %[[VAL_14]]) -> (!ttg.async.token)  : i32 {
// CHECK:             %[[VAL_25:.*]] = arith.muli %[[VAL_23]], %[[VAL_7]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : i32
// CHECK:             %[[VAL_26:.*]] = nvws.semaphore.acquire %[[VAL_17]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_27:.*]]:2 = nvws.semaphore.buffer %[[VAL_17]], %[[VAL_26]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>
// CHECK:             nvws.descriptor_load %[[VAL_3]]{{\[}}%[[VAL_1]], %[[VAL_25]]] 16384 %[[VAL_27]]#0 {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_10]]>>, i32, i32, !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>
// CHECK:             nvws.descriptor_load %[[VAL_4]]{{\[}}%[[VAL_2]], %[[VAL_25]]] 16384 %[[VAL_27]]#1 {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_10]]>>, i32, i32, !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_18]], %[[VAL_26]] [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_28:.*]] = nvws.semaphore.acquire %[[VAL_18]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_29:.*]]:2 = nvws.semaphore.buffer %[[VAL_18]], %[[VAL_28]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>
// CHECK:             %[[VAL_30:.*]] = ttg.memdesc_trans %[[VAL_29]]#1 {loop.cluster = 0 : i32, loop.stage = 1 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable> -> !ttg.memdesc<64x128xf16, #[[$ATTR_12]], #[[$ATTR_13]], mutable>
// CHECK:             %[[VAL_31:.*]] = arith.cmpi eq, %[[VAL_23]], %[[VAL_19]] {ttg.partition = array<i32: 1>} : i32
// CHECK:             %[[VAL_32:.*]] = ttng.tc_gen5_mma %[[VAL_29]]#0, %[[VAL_30]], %[[VAL_13]][], %[[VAL_10]], %[[VAL_10]], %[[VAL_21]]{{\[}}%[[VAL_31]]] {is_async, loop.cluster = 0 : i32, loop.stage = 1 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<64x128xf16, #[[$ATTR_12]], #[[$ATTR_13]], mutable>, !ttg.memdesc<128x128xf32, #[[$ATTR_14]], #ttng.tensor_memory, mutable>, !ttg.memdesc<1xi64, #[[$ATTR_11]], #[[$ATTR_13]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_17]], %[[VAL_28]] [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>, !ttg.memdesc<3x128x64xf16, #[[$ATTR_10]], #[[$ATTR_13]], mutable>], 3>, !ttg.async.token
// CHECK:             scf.yield %[[VAL_5]] : !ttg.async.token
// CHECK:           } {tt.num_stages = 2 : i32, tt.scheduled_max_stage = 1 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 1>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_15:.+]] = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
// CHECK: #[[$ATTR_16:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_17:.+]] = #ttg.shared_memory
  tt.func @warp_specialize_tma_matmul(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: !tt.tensordesc<tensor<128x64xf16, #shared>>, %arg4: !tt.tensordesc<tensor<128x64xf16, #shared>>) {
    %0 = ub.poison : !ttg.async.token
    %cst = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #blocked>
    %c64_i32 = arith.constant 64 : i32
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %true = arith.constant true
    %result, %token = ttng.tmem_alloc : () -> (!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>, !ttg.async.token)
    %1 = ttg.memdesc_index %result[%c0_i32] : !ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %2 = ttng.tmem_store %cst, %1[%token], %true : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %3 = ttg.local_alloc : () -> !ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>
    %4 = nvws.aref.create %3 : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>
    %5 = ttg.local_alloc : () -> !ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>
    %6 = nvws.aref.create %5 : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>
    %7 = arith.subi %arg0, %c1_i32 : i32
    %8 = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64, #shared1, #smem, mutable>
    %9 = ttg.memdesc_index %8[%c0_i32] : !ttg.memdesc<1x1xi64, #shared1, #smem, mutable> -> !ttg.memdesc<1xi64, #shared1, #smem, mutable>
    ttng.init_barrier %9, 1 : !ttg.memdesc<1xi64, #shared1, #smem, mutable>
    %10 = scf.for %arg5 = %c0_i32 to %arg0 step %c1_i32 iter_args(%arg6 = %2) -> (!ttg.async.token)  : i32 {
      %11 = arith.muli %arg5, %c64_i32 {ttg.partition = array<i32: 2>, loop.cluster = 1 : i32, loop.stage = 0 : i32} : i32
      %buffers, %token_2 = nvws.aref.put.enter %4[%c0_i32, %c0_i32] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>, !ttg.async.token
      nvws.descriptor_load %arg3[%arg1, %11] 16384 %buffers {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>>, i32, i32, !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
      nvws.aref.put.exit %4[%c0_i32], %token_2 [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_3, %token_4 = nvws.aref.get.enter %4[%c0_i32, %c0_i32] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.async.token
      %buffers_5, %token_6 = nvws.aref.put.enter %6[%c0_i32, %c0_i32] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>, !ttg.async.token
      nvws.descriptor_load %arg4[%arg2, %11] 16384 %buffers_5 {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>>, i32, i32, !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
      nvws.aref.put.exit %6[%c0_i32], %token_6 [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_7, %token_8 = nvws.aref.get.enter %6[%c0_i32, %c0_i32] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.async.token

      %12 = ttg.memdesc_trans %buffers_7 {loop.cluster = 0 : i32, loop.stage = 1 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem> -> !ttg.memdesc<64x128xf16, #shared2, #smem>
      %13 = arith.cmpi eq, %arg5, %7 {ttg.partition = array<i32: 1>} : i32
      %14 = ttng.tc_gen5_mma %buffers_3, %12, %1[], %true, %true, %9[%13] {is_async, loop.cluster = 0 : i32, loop.stage = 1 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.memdesc<64x128xf16, #shared2, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>, !ttg.memdesc<1xi64, #shared1, #smem, mutable>
      nvws.aref.get.exit %6[%c0_i32], %token_8 [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      nvws.aref.get.exit %4[%c0_i32], %token_4 [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      scf.yield %0 : !ttg.async.token
    } {tt.num_stages = 2 : i32, tt.scheduled_max_stage = 1 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 1>]}
    tt.return
  }
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func @load_used_as_reg_and_smem(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_16]]>>, %[[VAL_1:.*]]: i32) {
// CHECK:           %[[VAL_2:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_3:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_4:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_4]] true : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>
// CHECK:           %[[VAL_6:.*]] = nvws.semaphore.create %[[VAL_4]] false : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>
// CHECK:           scf.for %[[VAL_7:.*]] = %[[VAL_3]] to %[[VAL_1]] step %[[VAL_2]]  : i32 {
// CHECK:             %[[VAL_8:.*]] = nvws.semaphore.acquire %[[VAL_5]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_9:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_8]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>
// CHECK:             nvws.descriptor_load %[[VAL_0]]{{\[}}%[[VAL_7]], %[[VAL_7]]] 16384 %[[VAL_9]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_16]]>>, i32, i32, !ttg.memdesc<128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>
// CHECK:             nvws.semaphore.release %[[VAL_6]], %[[VAL_8]] [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_10:.*]] = nvws.semaphore.acquire %[[VAL_6]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_11:.*]] = nvws.semaphore.buffer %[[VAL_6]], %[[VAL_10]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>
// CHECK:             %[[VAL_12:.*]] = ttg.local_load %[[VAL_11]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable> -> tensor<128x64xf16, #[[$ATTR_15]]>
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_10]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_13:.*]] = nvws.semaphore.acquire %[[VAL_6]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_14:.*]] = nvws.semaphore.buffer %[[VAL_6]], %[[VAL_13]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>
// CHECK:             "use1"(%[[VAL_12]]) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : (tensor<128x64xf16, #[[$ATTR_15]]>) -> ()
// CHECK:             "use2"(%[[VAL_14]]) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : (!ttg.memdesc<128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>) -> ()
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_13]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_16]], #[[$ATTR_17]], mutable>], 3>, !ttg.async.token
// CHECK:           } {tt.num_stages = 2 : i32, tt.scheduled_max_stage = 1 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_18:.+]] = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
// CHECK: #[[$ATTR_19:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_20:.+]] = #ttg.shared_memory
  tt.func @load_used_as_reg_and_smem(%arg0: !tt.tensordesc<tensor<128x64xf16, #shared>>, %arg1: i32) {
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %0 = ttg.local_alloc : () -> !ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>
    %1 = nvws.aref.create %0 : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>
    scf.for %arg2 = %c0_i32 to %arg1 step %c1_i32  : i32 {
      %buffers, %token = nvws.aref.put.enter %1[%c0_i32, %c0_i32] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>, !ttg.async.token
      nvws.descriptor_load %arg0[%arg2, %arg2] 16384 %buffers {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>>, i32, i32, !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
      nvws.aref.put.exit %1[%c0_i32], %token [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_0, %token_1 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.async.token
      %2 = ttg.local_load %buffers_0 {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x64xf16, #shared, #smem> -> tensor<128x64xf16, #blocked>
      nvws.aref.get.exit %1[%c0_i32], %token_1 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_2, %token_3 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.async.token
      "use1"(%2) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : (tensor<128x64xf16, #blocked>) -> ()
      "use2"(%buffers_2) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : (!ttg.memdesc<128x64xf16, #shared, #smem>) -> ()
      nvws.aref.get.exit %1[%c0_i32], %token_3 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
    } {tt.num_stages = 2 : i32, tt.scheduled_max_stage = 1 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2>}
    tt.return
  }
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func @load_used_as_reg_and_smem_same_partition(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_19]]>>, %[[VAL_1:.*]]: i32) {
// CHECK:           %[[VAL_2:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_3:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_4:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>
// CHECK:           %[[VAL_5:.*]] = nvws.semaphore.create %[[VAL_4]] true : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3>
// CHECK:           %[[VAL_6:.*]] = nvws.semaphore.create %[[VAL_4]] false : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3>
// CHECK:           scf.for %[[VAL_7:.*]] = %[[VAL_3]] to %[[VAL_1]] step %[[VAL_2]]  : i32 {
// CHECK:             %[[VAL_8:.*]] = nvws.semaphore.acquire %[[VAL_5]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_9:.*]] = nvws.semaphore.buffer %[[VAL_5]], %[[VAL_8]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable, 1x128x64>
// CHECK:             nvws.descriptor_load %[[VAL_0]]{{\[}}%[[VAL_7]], %[[VAL_7]]] 16384 %[[VAL_9]] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_19]]>>, i32, i32, !ttg.memdesc<128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable, 1x128x64>
// CHECK:             nvws.semaphore.release %[[VAL_6]], %[[VAL_8]] [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_10:.*]] = nvws.semaphore.acquire %[[VAL_6]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_11:.*]] = nvws.semaphore.buffer %[[VAL_6]], %[[VAL_10]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable, 1x128x64>
// CHECK:             %[[VAL_12:.*]] = ttg.local_load %[[VAL_11]] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable, 1x128x64> -> tensor<128x64xf16, #[[$ATTR_18]]>
// CHECK:             "use1"(%[[VAL_12]]) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : (tensor<128x64xf16, #[[$ATTR_18]]>) -> ()
// CHECK:             "use2"(%[[VAL_11]]) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : (!ttg.memdesc<128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable, 1x128x64>) -> ()
// CHECK:             nvws.semaphore.release %[[VAL_5]], %[[VAL_10]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<3x128x64xf16, #[[$ATTR_19]], #[[$ATTR_20]], mutable>], 3>, !ttg.async.token
// CHECK:           } {tt.num_stages = 2 : i32, tt.scheduled_max_stage = 1 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_21:.+]] = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
// CHECK: #[[$ATTR_22:.+]] = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
// CHECK: #[[$ATTR_23:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_24:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
// CHECK: #[[$ATTR_25:.+]] = #ttg.shared_memory
// CHECK: #[[$ATTR_26:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
  tt.func @load_used_as_reg_and_smem_same_partition(%arg0: !tt.tensordesc<tensor<128x64xf16, #shared>>, %arg1: i32) {
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %0 = ttg.local_alloc : () -> !ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>
    %1 = nvws.aref.create %0 : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>
    scf.for %arg2 = %c0_i32 to %arg1 step %c1_i32  : i32 {
      %buffers, %token = nvws.aref.put.enter %1[%c0_i32, %c0_i32] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable, 1x128x64>, !ttg.async.token
      nvws.descriptor_load %arg0[%arg2, %arg2] 16384 %buffers {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : !tt.tensordesc<tensor<128x64xf16, #shared>>, i32, i32, !ttg.memdesc<128x64xf16, #shared, #smem, mutable, 1x128x64>
      nvws.aref.put.exit %1[%c0_i32], %token [#nvws.async_op<tma_load>] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_0, %token_1 = nvws.aref.get.enter %1[%c0_i32, %c0_i32] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<128x64xf16, #shared, #smem, 1x128x64>, !ttg.async.token
      %2 = ttg.local_load %buffers_0 {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x64xf16, #shared, #smem, 1x128x64> -> tensor<128x64xf16, #blocked>
      "use1"(%2) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : (tensor<128x64xf16, #blocked>) -> ()
      "use2"(%buffers_0) {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : (!ttg.memdesc<128x64xf16, #shared, #smem, 1x128x64>) -> ()
      nvws.aref.get.exit %1[%c0_i32], %token_1 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
    } {tt.num_stages = 2 : i32, tt.scheduled_max_stage = 1 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2>}
    tt.return
  }
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#blocked1 = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func @lower_aref_buffer(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_23]]>>, %[[VAL_1:.*]]: !tt.tensordesc<tensor<64x128xf16, #[[$ATTR_23]]>>) {
// CHECK:           %[[VAL_2:.*]] = arith.constant 32 : i32
// CHECK:           %[[VAL_3:.*]] = arith.constant dense<1.000000e+00> : tensor<128x128xf32, #[[$ATTR_21]]>
// CHECK:           %[[VAL_4:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #[[$ATTR_21]]>
// CHECK:           %[[VAL_5:.*]] = arith.constant true
// CHECK:           %[[VAL_6:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_7:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_8:.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_9:.*]] = nvws.semaphore.create %[[VAL_8]] true : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>
// CHECK:           %[[VAL_10:.*]] = nvws.semaphore.create %[[VAL_8]] false : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>
// CHECK:           %[[VAL_11:.*]] = nvws.semaphore.acquire %[[VAL_9]] : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2> -> !ttg.async.token
// CHECK:           %[[VAL_12:.*]] = nvws.semaphore.buffer %[[VAL_9]], %[[VAL_11]] : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:           %[[VAL_13:.*]] = nvws.semaphore.buffer %[[VAL_9]], %[[VAL_11]] : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:           %[[VAL_14:.*]] = ttng.tmem_store %[[VAL_4]], %[[VAL_13]][], %[[VAL_5]] : tensor<128x128xf32, #[[$ATTR_21]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:           %[[VAL_15:.*]] = scf.for %[[VAL_16:.*]] = %[[VAL_7]] to %[[VAL_2]] step %[[VAL_6]] iter_args(%[[VAL_17:.*]] = %[[VAL_11]]) -> (!ttg.async.token)  : i32 {
// CHECK:             %[[VAL_18:.*]]:3 = "get_offsets"(%[[VAL_16]]) {ttg.partition = array<i32: 2>} : (i32) -> (i32, i32, i32)
// CHECK:             %[[VAL_19:.*]] = tt.descriptor_load %[[VAL_0]]{{\[}}%[[VAL_18]]#0, %[[VAL_18]]#2] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_23]]>> -> tensor<128x64xf16, #[[$ATTR_22]]>
// CHECK:             %[[VAL_20:.*]] = tt.descriptor_load %[[VAL_1]]{{\[}}%[[VAL_18]]#1, %[[VAL_18]]#2] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<64x128xf16, #[[$ATTR_23]]>> -> tensor<64x128xf16, #[[$ATTR_22]]>
// CHECK:             %[[VAL_21:.*]] = ttg.local_alloc %[[VAL_19]] {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #[[$ATTR_22]]>) -> !ttg.memdesc<128x64xf16, #[[$ATTR_23]], #[[$ATTR_25]]>
// CHECK:             %[[VAL_22:.*]] = ttg.local_alloc %[[VAL_20]] {ttg.partition = array<i32: 2>} : (tensor<64x128xf16, #[[$ATTR_22]]>) -> !ttg.memdesc<64x128xf16, #[[$ATTR_23]], #[[$ATTR_25]]>
// CHECK:             %[[VAL_23:.*]] = nvws.semaphore.buffer %[[VAL_9]], %[[VAL_17]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:             %[[VAL_24:.*]] = ttng.tc_gen5_mma %[[VAL_21]], %[[VAL_22]], %[[VAL_23]][], %[[VAL_5]], %[[VAL_5]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_23]], #[[$ATTR_25]]>, !ttg.memdesc<64x128xf16, #[[$ATTR_23]], #[[$ATTR_25]]>, !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:             %[[VAL_25:.*]] = arith.cmpi eq, %[[VAL_16]], %[[VAL_7]] {ttg.partition = array<i32: 0, 1>} : i32
// CHECK:             %[[VAL_26:.*]] = scf.if %[[VAL_25]] -> (!ttg.async.token) {
// CHECK:               nvws.semaphore.release %[[VAL_10]], %[[VAL_17]] [#nvws.async_op<tc5mma>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token
// CHECK:               %[[VAL_27:.*]] = nvws.semaphore.acquire %[[VAL_10]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2> -> !ttg.async.token
// CHECK:               %[[VAL_28:.*]] = nvws.semaphore.buffer %[[VAL_10]], %[[VAL_27]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:               %[[VAL_29:.*]] = nvws.semaphore.buffer %[[VAL_10]], %[[VAL_27]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:               %[[VAL_30:.*]], %[[VAL_31:.*]] = ttng.tmem_load %[[VAL_29]][] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128> -> tensor<128x128xf32, #[[$ATTR_21]]>
// CHECK:               nvws.semaphore.release %[[VAL_9]], %[[VAL_27]] [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token
// CHECK:               "acc_user"(%[[VAL_30]]) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #[[$ATTR_21]]>) -> ()
// CHECK:               %[[VAL_32:.*]] = nvws.semaphore.acquire %[[VAL_9]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2> -> !ttg.async.token
// CHECK:               %[[VAL_33:.*]] = nvws.semaphore.buffer %[[VAL_9]], %[[VAL_32]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:               scf.yield %[[VAL_32]] : !ttg.async.token
// CHECK:             } else {
// CHECK:               scf.yield %[[VAL_17]] : !ttg.async.token
// CHECK:             } {ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 1>]}
// CHECK:             %[[VAL_34:.*]] = nvws.semaphore.buffer %[[VAL_9]], %[[VAL_26]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:             %[[VAL_35:.*]] = ttng.tmem_store %[[VAL_3]], %[[VAL_34]][], %[[VAL_5]] {ttg.partition = array<i32: 1>} : tensor<128x128xf32, #[[$ATTR_21]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 2x128x128>
// CHECK:             scf.yield %[[VAL_26]] : !ttg.async.token
// CHECK:           } {tt.num_stages = 2 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 1>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 5 : i32}
// CHECK:           nvws.semaphore.release %[[VAL_10]], %[[VAL_15]] [#nvws.async_op<none>] : <[!ttg.memdesc<2x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token
// CHECK:           tt.return
// CHECK:         }
  tt.func @lower_aref_buffer(%arg0: !tt.tensordesc<tensor<128x64xf16, #shared>>, %arg1: !tt.tensordesc<tensor<64x128xf16, #shared>>) {
    %c32_i32 = arith.constant 32 : i32
    %cst = arith.constant dense<1.000000e+00> : tensor<128x128xf32, #blocked>
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #blocked>
    %true = arith.constant true
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %result = ttng.tmem_alloc : () -> !ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %0 = nvws.aref.create %result : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>
    %buffers, %token = nvws.aref.put.enter %0 : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>, !ttg.async.token
    %1 = nvws.aref.buffer %0, %token : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
    %2 = ttng.tmem_store %cst_0, %1[], %true : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
    %3 = scf.for %arg2 = %c0_i32 to %c32_i32 step %c1_i32 iter_args(%arg3 = %token) -> (!ttg.async.token)  : i32 {
      %4:3 = "get_offsets"(%arg2) {ttg.partition = array<i32: 2>} : (i32) -> (i32, i32, i32)
      %5 = tt.descriptor_load %arg0[%4#0, %4#2] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>> -> tensor<128x64xf16, #blocked1>
      %6 = tt.descriptor_load %arg1[%4#1, %4#2] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<64x128xf16, #shared>> -> tensor<64x128xf16, #blocked1>
      %7 = ttg.local_alloc %5 {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #blocked1>) -> !ttg.memdesc<128x64xf16, #shared, #smem>
      %8 = ttg.local_alloc %6 {ttg.partition = array<i32: 2>} : (tensor<64x128xf16, #blocked1>) -> !ttg.memdesc<64x128xf16, #shared, #smem>
      %9 = nvws.aref.buffer %0, %arg3 {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
      %10 = ttng.tc_gen5_mma %7, %8, %9[], %true, %true {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.memdesc<64x128xf16, #shared, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
      %11 = arith.cmpi eq, %arg2, %c0_i32 {ttg.partition = array<i32: 0, 1>} : i32
      %12 = scf.if %11 -> (!ttg.async.token) {
        nvws.aref.put.exit %0, %arg3 [#nvws.async_op<tc5mma>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
        %buffers_1, %token_2 = nvws.aref.get.enter %0 {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>, !ttg.async.token
        %15 = nvws.aref.buffer %0, %token_2 {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
        %result_3, %token_4 = ttng.tmem_load %15[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128> -> tensor<128x128xf32, #blocked>
        nvws.aref.get.exit %0, %token_2 [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
        "acc_user"(%result_3) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #blocked>) -> ()
        %buffers_5, %token_6 = nvws.aref.put.enter %0 {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>, !ttg.async.token
        scf.yield %token_6 : !ttg.async.token
      } else {
        scf.yield %arg3 : !ttg.async.token
      } {ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 1>]}
      %13 = nvws.aref.buffer %0, %12 {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
      %14 = ttng.tmem_store %cst, %13[], %true {ttg.partition = array<i32: 1>} : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 2x128x128>
      scf.yield %12 : !ttg.async.token
    } {tt.num_stages = 2 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 5 : i32, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 1>]}
    nvws.aref.put.exit %0, %3 [#nvws.async_op<none>] : <[!ttg.memdesc<2x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    tt.return
  }


// CHECK-LABEL:   tt.func @aref_not_in_loop(
// CHECK-SAME:  %[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_23]]>>, %[[VAL_4:.*]]: !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_23]]>>) {
// CHECK:           %[[VAL_5:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #[[$ATTR_21]]>
// CHECK:           %[[VAL_6:.*]] = arith.constant 64 : i32
// CHECK:           %[[VAL_7:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_8:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_9:.*]] = arith.constant true
// CHECK:           %[[VAL_10:.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_11:.*]] = nvws.semaphore.create %[[VAL_10]] true : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>
// CHECK:           %[[VAL_12:.*]] = nvws.semaphore.create %[[VAL_10]] false : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>
// CHECK:           %[[VAL_13:.*]] = nvws.semaphore.acquire %[[VAL_11]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:           %[[VAL_14:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_13]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_15:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_13]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_16:.*]] = ttng.tmem_store %[[VAL_5]], %[[VAL_15]][], %[[VAL_9]] : tensor<128x128xf32, #[[$ATTR_21]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           scf.for %[[VAL_17:.*]] = %[[VAL_8]] to %[[VAL_0]] step %[[VAL_7]]  : i32 {
// CHECK:             %[[VAL_18:.*]] = arith.muli %[[VAL_17]], %[[VAL_6]] {ttg.partition = array<i32: 2>} : i32
// CHECK:             %[[VAL_19:.*]] = tt.descriptor_load %[[VAL_3]]{{\[}}%[[VAL_1]], %[[VAL_18]]] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_23]]>> -> tensor<128x64xf16, #[[$ATTR_22]]>
// CHECK:             %[[VAL_20:.*]] = tt.descriptor_load %[[VAL_4]]{{\[}}%[[VAL_2]], %[[VAL_18]]] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #[[$ATTR_23]]>> -> tensor<128x64xf16, #[[$ATTR_22]]>
// CHECK:             %[[VAL_21:.*]] = ttg.local_alloc %[[VAL_19]] {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #[[$ATTR_22]]>) -> !ttg.memdesc<128x64xf16, #[[$ATTR_23]], #[[$ATTR_25]]>
// CHECK:             %[[VAL_22:.*]] = ttg.local_alloc %[[VAL_20]] {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #[[$ATTR_22]]>) -> !ttg.memdesc<128x64xf16, #[[$ATTR_23]], #[[$ATTR_25]]>
// CHECK:             %[[VAL_23:.*]] = ttg.memdesc_trans %[[VAL_22]] {order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_23]], #[[$ATTR_25]]> -> !ttg.memdesc<64x128xf16, #[[$ATTR_24]], #[[$ATTR_25]]>
// CHECK:             %[[VAL_24:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_13]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_25:.*]] = ttng.tc_gen5_mma %[[VAL_21]], %[[VAL_23]], %[[VAL_24]][], %[[VAL_9]], %[[VAL_9]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_23]], #[[$ATTR_25]]>, !ttg.memdesc<64x128xf16, #[[$ATTR_24]], #[[$ATTR_25]]>, !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           } {tt.num_stages = 2 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           nvws.semaphore.release %[[VAL_12]], %[[VAL_13]] [#nvws.async_op<tc5mma>] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:           %[[VAL_26:.*]] = nvws.semaphore.acquire %[[VAL_12]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:           %[[VAL_27:.*]] = nvws.semaphore.buffer %[[VAL_12]], %[[VAL_26]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_28:.*]] = nvws.semaphore.buffer %[[VAL_12]], %[[VAL_26]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_29:.*]], %[[VAL_30:.*]] = ttng.tmem_load %[[VAL_28]][] : !ttg.memdesc<128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_21]]>
// CHECK:           nvws.semaphore.release %[[VAL_11]], %[[VAL_26]] [#nvws.async_op<none>] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_26]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:           "use"(%[[VAL_29]]) : (tensor<128x128xf32, #[[$ATTR_21]]>) -> ()
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_27:.+]] = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
// CHECK: #[[$ATTR_28:.+]] = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
// CHECK: #[[$ATTR_29:.+]] = #ttg.linear<{{.*register = \[\[1, 0\], \[2, 0\], \[0, 32\], \[0, 64\], \[4, 0\]\].*lane = \[\[0, 1\], \[0, 2\], \[0, 4\], \[0, 8\], \[0, 16\]\].*warp = \[\[0, 0\], \[0, 0\]\].*block = \[\].*}}>
// CHECK: #[[$ATTR_30:.+]] = #ttg.linear<{{.*register = \[\[0, 1\], \[0, 2\], \[32, 0\], \[64, 0\], \[0, 4\]\].*lane = \[\[1, 0\], \[2, 0\], \[4, 0\], \[8, 0\], \[16, 0\]\].*warp = \[\[0, 0\], \[0, 0\]\].*block = \[\].*}}>
// CHECK: #[[$ATTR_31:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_32:.+]] = #ttg.shared_memory
// CHECK: #[[$ATTR_33:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
// CHECK: #[[$ATTR_34:.+]] = #ttng.tensor_memory_scales_encoding<>
  tt.func @aref_not_in_loop(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: !tt.tensordesc<tensor<128x64xf16, #shared>>, %arg4: !tt.tensordesc<tensor<128x64xf16, #shared>>) {
    %cst = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #blocked>
    %c64_i32 = arith.constant 64 : i32
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %true = arith.constant true
    %result = ttng.tmem_alloc : () -> !ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %0 = nvws.aref.create %result : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>
    %buffers, %token = nvws.aref.put.enter %0 : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.async.token
    %1 = nvws.aref.buffer %0, %token : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    %2 = ttng.tmem_store %cst, %1[], %true : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    scf.for %arg5 = %c0_i32 to %arg0 step %c1_i32  : i32 {
      %4 = arith.muli %arg5, %c64_i32 {ttg.partition = array<i32: 2>} : i32
      %5 = tt.descriptor_load %arg3[%arg1, %4] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>> -> tensor<128x64xf16, #blocked1>
      %6 = tt.descriptor_load %arg4[%arg2, %4] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<128x64xf16, #shared>> -> tensor<128x64xf16, #blocked1>
      %7 = ttg.local_alloc %5 {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #blocked1>) -> !ttg.memdesc<128x64xf16, #shared, #smem>
      %8 = ttg.local_alloc %6 {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #blocked1>) -> !ttg.memdesc<128x64xf16, #shared, #smem>
      %9 = ttg.memdesc_trans %8 {order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem> -> !ttg.memdesc<64x128xf16, #shared1, #smem>
      %10 = nvws.aref.buffer %0, %token {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
      %11 = ttng.tc_gen5_mma %7, %9, %10[], %true, %true {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.memdesc<64x128xf16, #shared1, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    } {tt.num_stages = 2 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2>}
    nvws.aref.put.exit %0, %token [#nvws.async_op<tc5mma>] : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    %buffers_0, %token_1 = nvws.aref.get.enter %0 : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.async.token
    %3 = nvws.aref.buffer %0, %token_1 : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    %result_2, %token_3 = ttng.tmem_load %3[] : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #blocked>
    nvws.aref.get.exit %0, %token_1 [#nvws.async_op<none>] : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    "use"(%result_2) : (tensor<128x128xf32, #blocked>) -> ()
    tt.return
  }

}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#blocked1 = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [1, 32], warpsPerCTA = [2, 2], order = [1, 0]}>
#linear = #ttg.linear<{register = [[0, 1], [0, 2], [32, 0], [64, 0], [0, 4]], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[0, 0], [0, 0]], block = []}>
#linear1 = #ttg.linear<{register = [[1, 0], [2, 0], [0, 32], [0, 64], [4, 0]], lane = [[0, 1], [0, 2], [0, 4], [0, 8], [0, 16]], warp = [[0, 0], [0, 0]], block = []}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
#tmem_scales = #ttng.tensor_memory_scales_encoding<>
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {

// CHECK-LABEL:   tt.func @load_scale_mma_user(
// CHECK-SAME:  %[[VAL_0:.*]]: !ttg.memdesc<128x64xf16, #[[$ATTR_31]], #[[$ATTR_32]]>, %[[VAL_1:.*]]: !ttg.memdesc<64x128xf16, #[[$ATTR_31]], #[[$ATTR_32]]>, %[[VAL_2:.*]]: !tt.tensordesc<tensor<8x128xi8, #[[$ATTR_31]]>>, %[[VAL_3:.*]]: !ttg.memdesc<128x8xi8, #[[$ATTR_34]], #ttng.tensor_memory>, %[[VAL_4:.*]]: i32) {
// CHECK:           %[[VAL_5:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #[[$ATTR_27]]>
// CHECK:           %[[VAL_6:.*]] = arith.constant true
// CHECK:           %[[VAL_7:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_8:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_9:.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_10:.*]] = nvws.semaphore.create %[[VAL_9]] true : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>
// CHECK:           %[[VAL_11:.*]] = nvws.semaphore.create %[[VAL_9]] false : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>
// CHECK:           %[[VAL_12:.*]] = nvws.semaphore.acquire %[[VAL_10]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:           %[[VAL_13:.*]] = nvws.semaphore.buffer %[[VAL_10]], %[[VAL_12]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_14:.*]] = nvws.semaphore.buffer %[[VAL_10]], %[[VAL_12]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_15:.*]] = ttng.tmem_store %[[VAL_5]], %[[VAL_14]][], %[[VAL_6]] : tensor<128x128xf32, #[[$ATTR_27]]> -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_16:.*]] = scf.for %[[VAL_17:.*]] = %[[VAL_8]] to %[[VAL_4]] step %[[VAL_7]] iter_args(%[[VAL_18:.*]] = %[[VAL_12]]) -> (!ttg.async.token)  : i32 {
// CHECK:             %[[VAL_19:.*]] = tt.descriptor_load %[[VAL_2]]{{\[}}%[[VAL_17]], %[[VAL_17]]] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<8x128xi8, #[[$ATTR_31]]>> -> tensor<8x128xi8, #[[$ATTR_28]]>
// CHECK:             %[[VAL_20:.*]] = ttg.local_alloc %[[VAL_19]] {ttg.partition = array<i32: 2>} : (tensor<8x128xi8, #[[$ATTR_28]]>) -> !ttg.memdesc<8x128xi8, #[[$ATTR_31]], #[[$ATTR_32]]>
// CHECK:             %[[VAL_21:.*]] = ttg.local_load %[[VAL_20]] {ttg.partition = array<i32: 0>} : !ttg.memdesc<8x128xi8, #[[$ATTR_31]], #[[$ATTR_32]]> -> tensor<8x128xi8, #[[$ATTR_29]]>
// CHECK:             %[[VAL_22:.*]] = tt.trans %[[VAL_21]] {order = array<i32: 1, 0>, ttg.partition = array<i32: 0>} : tensor<8x128xi8, #[[$ATTR_29]]> -> tensor<128x8xi8, #[[$ATTR_30]]>
// CHECK:             %[[VAL_23:.*]] = ttng.tmem_alloc %[[VAL_22]] {ttg.partition = array<i32: 0, 1>} : (tensor<128x8xi8, #[[$ATTR_30]]>) -> !ttg.memdesc<128x8xi8, #[[$ATTR_34]], #ttng.tensor_memory>
// CHECK:             %[[VAL_24:.*]] = nvws.semaphore.buffer %[[VAL_10]], %[[VAL_18]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_25:.*]] = ttng.tc_gen5_mma_scaled %[[VAL_0]], %[[VAL_1]], %[[VAL_24]][], %[[VAL_23]], %[[VAL_3]], %[[VAL_6]], %[[VAL_6]] lhs = e4m3 rhs = e4m3 {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #[[$ATTR_31]], #[[$ATTR_32]]>, !ttg.memdesc<64x128xf16, #[[$ATTR_31]], #[[$ATTR_32]]>, !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x8xi8, #[[$ATTR_34]], #ttng.tensor_memory>, !ttg.memdesc<128x8xi8, #[[$ATTR_34]], #ttng.tensor_memory>
// CHECK:             nvws.semaphore.release %[[VAL_11]], %[[VAL_18]] [#nvws.async_op<tc5mma>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_26:.*]] = nvws.semaphore.acquire %[[VAL_11]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_27:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_26]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_28:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_26]] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             %[[VAL_29:.*]], %[[VAL_30:.*]] = ttng.tmem_load %[[VAL_28]][] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_27]]>
// CHECK:             nvws.semaphore.release %[[VAL_10]], %[[VAL_26]] [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:             "user"(%[[VAL_29]]) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #[[$ATTR_27]]>) -> ()
// CHECK:             %[[VAL_31:.*]] = nvws.semaphore.acquire %[[VAL_10]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_32:.*]] = nvws.semaphore.buffer %[[VAL_10]], %[[VAL_31]] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:             scf.yield %[[VAL_31]] : !ttg.async.token
// CHECK:           } {tt.num_stages = 3 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 1>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 16 : i32}
// CHECK:           nvws.semaphore.release %[[VAL_11]], %[[VAL_16]] [#nvws.async_op<none>] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:           %[[VAL_33:.*]] = nvws.semaphore.acquire %[[VAL_11]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:           %[[VAL_34:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_33]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_35:.*]] = nvws.semaphore.buffer %[[VAL_11]], %[[VAL_33]] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128>
// CHECK:           %[[VAL_36:.*]], %[[VAL_37:.*]] = ttng.tmem_load %[[VAL_35]][] : !ttg.memdesc<128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #[[$ATTR_27]]>
// CHECK:           nvws.semaphore.release %[[VAL_10]], %[[VAL_33]] [#nvws.async_op<none>] : <[!ttg.memdesc<1x128x128xf32, #[[$ATTR_33]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:           "use"(%[[VAL_36]]) : (tensor<128x128xf32, #[[$ATTR_27]]>) -> ()
// CHECK:           tt.return
// CHECK:         }
// CHECK: #[[$ATTR_35:.+]] = #ttg.blocked<{sizePerThread = [1, 64], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
// CHECK: #[[$ATTR_36:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
// CHECK: #[[$ATTR_37:.+]] = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
// CHECK: #[[$ATTR_38:.+]] = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
// CHECK: #[[$ATTR_39:.+]] = #ttg.shared_memory
// CHECK: #[[$ATTR_40:.+]] = #ttng.tensor_memory_encoding<blockM = 128, blockN = 64, colStride = 1>
  tt.func @load_scale_mma_user(%arg0: !ttg.memdesc<128x64xf16, #shared, #smem>, %arg1: !ttg.memdesc<64x128xf16, #shared, #smem>, %arg2: !tt.tensordesc<tensor<8x128xi8, #shared>>, %arg3: !ttg.memdesc<128x8xi8, #tmem_scales, #ttng.tensor_memory>, %arg4: i32) {
    %cst = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #blocked>
    %true = arith.constant true
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %result = ttng.tmem_alloc : () -> !ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %0 = nvws.aref.create %result : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>
    %buffers, %token = nvws.aref.put.enter %0 : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.async.token
    %1 = nvws.aref.buffer %0, %token : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    %2 = ttng.tmem_store %cst, %1[], %true : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    %3 = scf.for %arg5 = %c0_i32 to %arg4 step %c1_i32 iter_args(%arg6 = %token) -> (!ttg.async.token)  : i32 {
      %5 = tt.descriptor_load %arg2[%arg5, %arg5] {ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<8x128xi8, #shared>> -> tensor<8x128xi8, #blocked1>
      %6 = ttg.local_alloc %5 {ttg.partition = array<i32: 2>} : (tensor<8x128xi8, #blocked1>) -> !ttg.memdesc<8x128xi8, #shared, #smem>
      %7 = ttg.local_load %6 {ttg.partition = array<i32: 0>} : !ttg.memdesc<8x128xi8, #shared, #smem> -> tensor<8x128xi8, #linear1>
      %8 = tt.trans %7 {order = array<i32: 1, 0>, ttg.partition = array<i32: 0>} : tensor<8x128xi8, #linear1> -> tensor<128x8xi8, #linear>
      %result_4 = ttng.tmem_alloc %8 {ttg.partition = array<i32: 0, 1>} : (tensor<128x8xi8, #linear>) -> !ttg.memdesc<128x8xi8, #tmem_scales, #ttng.tensor_memory>
      %9 = nvws.aref.buffer %0, %arg6 {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
      %10 = ttng.tc_gen5_mma_scaled %arg0, %arg1, %9[], %result_4, %arg3, %true, %true lhs = e4m3 rhs = e4m3 {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.memdesc<64x128xf16, #shared, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.memdesc<128x8xi8, #tmem_scales, #ttng.tensor_memory>, !ttg.memdesc<128x8xi8, #tmem_scales, #ttng.tensor_memory>
      nvws.aref.put.exit %0, %arg6 [#nvws.async_op<tc5mma>] {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
      %buffers_5, %token_6 = nvws.aref.get.enter %0 {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.async.token
      %11 = nvws.aref.buffer %0, %token_6 {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
      %result_7, %token_8 = ttng.tmem_load %11[] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #blocked>
      nvws.aref.get.exit %0, %token_6 [#nvws.async_op<none>] {ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
      "user"(%result_7) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #blocked>) -> ()
      %buffers_9, %token_10 = nvws.aref.put.enter %0 {ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.async.token
      scf.yield %token_10 : !ttg.async.token
    } {tt.num_stages = 3 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 16 : i32, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 1>]}
    nvws.aref.put.exit %0, %3 [#nvws.async_op<none>] : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    %buffers_0, %token_1 = nvws.aref.get.enter %0 : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>, !ttg.async.token
    %4 = nvws.aref.buffer %0, %token_1 : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128>
    %result_2, %token_3 = ttng.tmem_load %4[] : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable, 1x128x128> -> tensor<128x128xf32, #blocked>
    nvws.aref.get.exit %0, %token_1 [#nvws.async_op<none>] : <[!ttg.memdesc<1x128x128xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    "use"(%result_2) : (tensor<128x128xf32, #blocked>) -> ()
    tt.return
  }

}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 64], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#shared2 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 64, colStride = 1>
module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
// CHECK-LABEL:   tt.func public @attention_forward(
// CHECK-SAME:  %[[VAL_0:.*]]: !ttg.memdesc<256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]]>, %[[VAL_1:.*]]: !tt.tensordesc<tensor<64x64xf16, #[[$ATTR_36]]>>, %[[VAL_2:.*]]: !tt.tensordesc<tensor<64x64xf16, #[[$ATTR_36]]>>, %[[VAL_3:.*]]: f32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: !tt.ptr<f32>) {
// CHECK:           %[[VAL_6:.*]] = arith.constant dense<1.000000e+00> : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:           %[[VAL_7:.*]] = arith.constant dense<0.000000e+00> : tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:           %[[VAL_8:.*]] = arith.constant dense<0xFF800000> : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:           %[[VAL_9:.*]] = arith.constant 64 : i32
// CHECK:           %[[VAL_10:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_11:.*]] = arith.constant false
// CHECK:           %[[VAL_12:.*]] = arith.constant true
// CHECK:           %[[VAL_13:.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_14:.*]] = nvws.semaphore.create %[[VAL_13]] true : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>
// CHECK:           %[[VAL_15:.*]] = nvws.semaphore.create %[[VAL_13]] false : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>
// CHECK:           %[[VAL_16:.*]] = nvws.semaphore.acquire %[[VAL_14]] : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2> -> !ttg.async.token
// CHECK:           %[[VAL_17:.*]] = nvws.semaphore.buffer %[[VAL_14]], %[[VAL_16]] : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64>
// CHECK:           %[[VAL_18:.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>
// CHECK:           %[[VAL_19:.*]] = nvws.semaphore.create %[[VAL_18]] true : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>
// CHECK:           %[[VAL_20:.*]] = nvws.semaphore.create %[[VAL_18]] false : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>
// CHECK:           %[[VAL_21:.*]] = nvws.semaphore.acquire %[[VAL_19]] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:           %[[VAL_22:.*]] = nvws.semaphore.buffer %[[VAL_19]], %[[VAL_21]] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:           %[[VAL_23:.*]] = nvws.semaphore.buffer %[[VAL_19]], %[[VAL_21]] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:           %[[VAL_24:.*]] = ttng.tmem_store %[[VAL_7]], %[[VAL_23]][], %[[VAL_12]] : tensor<256x64xf32, #[[$ATTR_35]]> -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:           %[[VAL_25:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>
// CHECK:           %[[VAL_26:.*]] = nvws.semaphore.create %[[VAL_25]] true : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>
// CHECK:           %[[VAL_27:.*]] = nvws.semaphore.create %[[VAL_25]] false : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>
// CHECK:           %[[VAL_28:.*]] = ttg.local_alloc : () -> !ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>
// CHECK:           %[[VAL_29:.*]] = nvws.semaphore.create %[[VAL_28]] true : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>
// CHECK:           %[[VAL_30:.*]] = nvws.semaphore.create %[[VAL_28]] false : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>
// CHECK:           %[[VAL_31:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>
// CHECK:           %[[VAL_32:.*]] = nvws.semaphore.create %[[VAL_31]] true : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],>
// CHECK:           %[[VAL_33:.*]] = nvws.semaphore.create %[[VAL_31]] false : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],>
// CHECK:           %[[VAL_34:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>
// CHECK:           %[[VAL_35:.*]] = nvws.semaphore.create %[[VAL_34]] true : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>
// CHECK:           %[[VAL_36:.*]] = nvws.semaphore.create %[[VAL_34]] false : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>
// CHECK:           %[[VAL_37:.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>
// CHECK:           %[[VAL_38:.*]] = nvws.semaphore.create %[[VAL_37]] true : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>
// CHECK:           %[[VAL_39:.*]] = nvws.semaphore.create %[[VAL_37]] false : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>
// CHECK:           %[[VAL_40:.*]]:4 = scf.for %[[VAL_41:.*]] = %[[VAL_10]] to %[[VAL_4]] step %[[VAL_9]] iter_args(%[[VAL_42:.*]] = %[[VAL_6]], %[[VAL_43:.*]] = %[[VAL_8]], %[[VAL_44:.*]] = %[[VAL_16]], %[[VAL_45:.*]] = %[[VAL_21]]) -> (tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>, !ttg.async.token, !ttg.async.token)  : i32 {
// CHECK:             %[[VAL_46:.*]] = nvws.semaphore.acquire %[[VAL_35]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_47:.*]] = nvws.semaphore.buffer %[[VAL_35]], %[[VAL_46]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token -> !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256>
// CHECK:             ttg.local_store %[[VAL_43]], %[[VAL_47]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>> -> !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256>
// CHECK:             nvws.semaphore.release %[[VAL_36]], %[[VAL_46]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_48:.*]] = nvws.semaphore.acquire %[[VAL_26]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_49:.*]] = nvws.semaphore.buffer %[[VAL_26]], %[[VAL_48]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             nvws.descriptor_load %[[VAL_1]]{{\[}}%[[VAL_41]], %[[VAL_10]]] 8192 %[[VAL_49]] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<64x64xf16, #[[$ATTR_36]]>>, i32, i32, !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             nvws.semaphore.release %[[VAL_27]], %[[VAL_48]] [#nvws.async_op<tma_load>] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_50:.*]] = nvws.semaphore.acquire %[[VAL_27]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_51:.*]] = nvws.semaphore.buffer %[[VAL_27]], %[[VAL_50]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             %[[VAL_52:.*]] = ttg.memdesc_trans %[[VAL_51]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64> -> !ttg.memdesc<64x64xf16, #[[$ATTR_38]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             %[[VAL_53:.*]] = nvws.semaphore.buffer %[[VAL_14]], %[[VAL_44]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64>
// CHECK:             %[[VAL_54:.*]] = ttng.tc_gen5_mma %[[VAL_0]], %[[VAL_52]], %[[VAL_53]][], %[[VAL_11]], %[[VAL_12]] {is_async, loop.cluster = 2 : i32, loop.stage = 2 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]]>, !ttg.memdesc<64x64xf16, #[[$ATTR_38]], #[[$ATTR_39]], mutable, 1x64x64>, !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64>
// CHECK:             nvws.semaphore.release %[[VAL_15]], %[[VAL_44]] [#nvws.async_op<tc5mma>] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_26]], %[[VAL_50]] [#nvws.async_op<tc5mma>] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_55:.*]] = nvws.semaphore.acquire %[[VAL_15]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2> -> !ttg.async.token
// CHECK:             %[[VAL_56:.*]] = nvws.semaphore.buffer %[[VAL_15]], %[[VAL_55]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64>
// CHECK:             %[[VAL_57:.*]] = nvws.semaphore.buffer %[[VAL_15]], %[[VAL_55]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64>
// CHECK:             %[[VAL_58:.*]], %[[VAL_59:.*]] = ttng.tmem_load %[[VAL_57]][] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64> -> tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             nvws.semaphore.release %[[VAL_14]], %[[VAL_55]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token
// CHECK:             %[[VAL_60:.*]] = "compute_row_max"(%[[VAL_58]], %[[VAL_3]]) {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : (tensor<256x64xf32, #[[$ATTR_35]]>, f32) -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_61:.*]] = nvws.semaphore.acquire %[[VAL_38]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_62:.*]] = nvws.semaphore.buffer %[[VAL_38]], %[[VAL_61]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token -> !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256>
// CHECK:             ttg.local_store %[[VAL_60]], %[[VAL_62]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>> -> !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256>
// CHECK:             nvws.semaphore.release %[[VAL_39]], %[[VAL_61]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_63:.*]] = "sub_row_max"(%[[VAL_58]], %[[VAL_60]], %[[VAL_3]]) {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : (tensor<256x64xf32, #[[$ATTR_35]]>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>, f32) -> tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_64:.*]] = math.exp2 %[[VAL_63]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_65:.*]] = nvws.semaphore.acquire %[[VAL_36]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_66:.*]] = nvws.semaphore.buffer %[[VAL_36]], %[[VAL_65]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token -> !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256>
// CHECK:             %[[VAL_67:.*]] = ttg.local_load %[[VAL_66]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256> -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             nvws.semaphore.release %[[VAL_35]], %[[VAL_65]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_68:.*]] = nvws.semaphore.acquire %[[VAL_39]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_69:.*]] = nvws.semaphore.buffer %[[VAL_39]], %[[VAL_68]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token -> !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256>
// CHECK:             %[[VAL_70:.*]] = ttg.local_load %[[VAL_69]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : !ttg.memdesc<256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable, 1x256> -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             nvws.semaphore.release %[[VAL_38]], %[[VAL_68]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_71:.*]] = arith.subf %[[VAL_67]], %[[VAL_70]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_72:.*]] = arith.subf %[[VAL_43]], %[[VAL_60]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_73:.*]] = math.exp2 %[[VAL_71]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_74:.*]] = math.exp2 %[[VAL_72]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_75:.*]] = "tt.reduce"(%[[VAL_64]]) <{axis = 1 : i32}> ({
// CHECK:             ^bb0(%[[VAL_76:.*]]: f32, %[[VAL_77:.*]]: f32):
// CHECK:               %[[VAL_78:.*]] = arith.addf %[[VAL_76]], %[[VAL_77]] {ttg.partition = array<i32: 0>} : f32
// CHECK:               tt.reduce.return %[[VAL_78]] {ttg.partition = array<i32: 0>} : f32
// CHECK:             }) {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>, ttg.partition.outputs = [array<i32: 0>]} : (tensor<256x64xf32, #[[$ATTR_35]]>) -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_79:.*]] = arith.mulf %[[VAL_42]], %[[VAL_74]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_80:.*]] = arith.addf %[[VAL_79]], %[[VAL_75]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>
// CHECK:             %[[VAL_81:.*]] = tt.expand_dims %[[VAL_73]] {axis = 1 : i32, loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>> -> tensor<256x1xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_82:.*]] = tt.broadcast %[[VAL_81]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x1xf32, #[[$ATTR_35]]> -> tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_83:.*]] = tt.addptr %[[VAL_5]], %[[VAL_41]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 0, 1, 2, 3>} : !tt.ptr<f32>, i32
// CHECK:             %[[VAL_84:.*]] = tt.load %[[VAL_83]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 0, 1, 2, 3>} : !tt.ptr<f32>
// CHECK:             %[[VAL_85:.*]] = tt.splat %[[VAL_84]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : f32 -> tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_86:.*]] = nvws.semaphore.buffer %[[VAL_19]], %[[VAL_45]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:             %[[VAL_87:.*]], %[[VAL_88:.*]] = ttng.tmem_load %[[VAL_86]][] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64> -> tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_89:.*]] = arith.mulf %[[VAL_87]], %[[VAL_82]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_90:.*]] = arith.addf %[[VAL_89]], %[[VAL_85]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:             %[[VAL_91:.*]] = nvws.semaphore.acquire %[[VAL_29]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_92:.*]] = nvws.semaphore.buffer %[[VAL_29]], %[[VAL_91]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             nvws.descriptor_load %[[VAL_2]]{{\[}}%[[VAL_41]], %[[VAL_10]]] 8192 %[[VAL_92]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<64x64xf16, #[[$ATTR_36]]>>, i32, i32, !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             nvws.semaphore.release %[[VAL_30]], %[[VAL_91]] [#nvws.async_op<tma_load>] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_93:.*]] = nvws.semaphore.acquire %[[VAL_30]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3> -> !ttg.async.token
// CHECK:             %[[VAL_94:.*]] = nvws.semaphore.buffer %[[VAL_30]], %[[VAL_93]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token -> !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>
// CHECK:             %[[VAL_95:.*]] = arith.truncf %[[VAL_64]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256x64xf32, #[[$ATTR_35]]> to tensor<256x64xf16, #[[$ATTR_35]]>
// CHECK:             %[[VAL_96:.*]] = nvws.semaphore.acquire %[[VAL_32]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_97:.*]] = nvws.semaphore.buffer %[[VAL_32]], %[[VAL_96]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x256x64>
// CHECK:             ttg.local_store %[[VAL_95]], %[[VAL_97]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256x64xf16, #[[$ATTR_35]]> -> !ttg.memdesc<256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x256x64>
// CHECK:             nvws.semaphore.release %[[VAL_33]], %[[VAL_96]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_98:.*]] = nvws.semaphore.acquire %[[VAL_33]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_99:.*]] = nvws.semaphore.buffer %[[VAL_33]], %[[VAL_98]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x256x64>
// CHECK:             %[[VAL_100:.*]] = ttng.tmem_store %[[VAL_90]], %[[VAL_86]][], %[[VAL_12]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x64xf32, #[[$ATTR_35]]> -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:             nvws.semaphore.release %[[VAL_20]], %[[VAL_45]] [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:             %[[VAL_101:.*]] = nvws.semaphore.acquire %[[VAL_20]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_102:.*]] = nvws.semaphore.buffer %[[VAL_20]], %[[VAL_101]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:             %[[VAL_103:.*]] = nvws.semaphore.buffer %[[VAL_20]], %[[VAL_101]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:             %[[VAL_104:.*]] = ttng.tc_gen5_mma %[[VAL_99]], %[[VAL_94]], %[[VAL_103]][], %[[VAL_12]], %[[VAL_12]] {is_async, loop.cluster = 0 : i32, loop.stage = 4 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x256x64>, !ttg.memdesc<64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable, 1x64x64>, !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:             nvws.semaphore.release %[[VAL_19]], %[[VAL_101]] [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_32]], %[[VAL_98]] [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>],>, !ttg.async.token
// CHECK:             nvws.semaphore.release %[[VAL_29]], %[[VAL_93]] [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<3x64x64xf16, #[[$ATTR_36]], #[[$ATTR_39]], mutable>], 3>, !ttg.async.token
// CHECK:             %[[VAL_105:.*]] = nvws.semaphore.acquire %[[VAL_14]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2> -> !ttg.async.token
// CHECK:             %[[VAL_106:.*]] = nvws.semaphore.buffer %[[VAL_14]], %[[VAL_105]] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 2x256x64>
// CHECK:             %[[VAL_107:.*]] = nvws.semaphore.acquire %[[VAL_19]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:             %[[VAL_108:.*]] = nvws.semaphore.buffer %[[VAL_19]], %[[VAL_107]] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:             scf.yield {ttg.partition = array<i32: 0, 1, 2, 3>} %[[VAL_80]], %[[VAL_60]], %[[VAL_105]], %[[VAL_107]] : tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>, !ttg.async.token, !ttg.async.token
// CHECK:           } {tt.scheduled_max_stage = 4 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2, 3>, ttg.partition.outputs = [array<i32: 0>, array<i32: 0>, array<i32: 1>, array<i32: 3>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32, 1 : i32], ttg.warp_specialize.tag = 0 : i32}
// CHECK:           ttg.local_dealloc %[[VAL_37]] : !ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>
// CHECK:           ttg.local_dealloc %[[VAL_34]] : !ttg.memdesc<1x256xf32, #[[$ATTR_37]], #[[$ATTR_39]], mutable>
// CHECK:           nvws.semaphore.release %[[VAL_20]], %[[VAL_109:.*]]#3 [#nvws.async_op<tc5mma>] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:           nvws.semaphore.release %[[VAL_15]], %[[VAL_109]]#2 [#nvws.async_op<none>] : <[!ttg.memdesc<2x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>], 2>, !ttg.async.token
// CHECK:           %[[VAL_110:.*]] = nvws.semaphore.acquire %[[VAL_20]] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],> -> !ttg.async.token
// CHECK:           %[[VAL_111:.*]] = nvws.semaphore.buffer %[[VAL_20]], %[[VAL_110]] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:           %[[VAL_112:.*]] = nvws.semaphore.buffer %[[VAL_20]], %[[VAL_110]] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64>
// CHECK:           %[[VAL_113:.*]], %[[VAL_114:.*]] = ttng.tmem_load %[[VAL_112]][] : !ttg.memdesc<256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable, 1x256x64> -> tensor<256x64xf32, #[[$ATTR_35]]>
// CHECK:           nvws.semaphore.release %[[VAL_19]], %[[VAL_110]] [#nvws.async_op<none>] : <[!ttg.memdesc<1x256x64xf32, #[[$ATTR_40]], #ttng.tensor_memory, mutable>],>, !ttg.async.token
// CHECK:           "use"(%[[VAL_109]]#0, %[[VAL_113]], %[[VAL_109]]#1) : (tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>, tensor<256x64xf32, #[[$ATTR_35]]>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #[[$ATTR_35]]}>>) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func public @attention_forward(%arg0: !ttg.memdesc<256x64xf16, #shared, #smem>, %arg1: !tt.tensordesc<tensor<64x64xf16, #shared>>, %arg2: !tt.tensordesc<tensor<64x64xf16, #shared>>, %arg3: f32, %arg4: i32, %arg5: !tt.ptr<f32>) {
    %cst = arith.constant dense<1.000000e+00> : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<256x64xf32, #blocked>
    %cst_1 = arith.constant dense<0xFF800000> : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
    %c64_i32 = arith.constant 64 : i32
    %c0_i32 = arith.constant 0 : i32
    %false = arith.constant false
    %true = arith.constant true
    %result = ttng.tmem_alloc : () -> !ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>
    %0 = nvws.aref.create %result : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>
    %buffers, %token = nvws.aref.put.enter %0 : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64>, !ttg.async.token
    %result_2 = ttng.tmem_alloc : () -> !ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>
    %1 = nvws.aref.create %result_2 : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>
    %buffers_3, %token_4 = nvws.aref.put.enter %1 : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>, !ttg.async.token
    %2 = nvws.aref.buffer %1, %token_4 : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
    %3 = ttng.tmem_store %cst_0, %2[], %true : tensor<256x64xf32, #blocked> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
    %4 = ttg.local_alloc : () -> !ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>
    %5 = nvws.aref.create %4 : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]>
    %6 = ttg.local_alloc : () -> !ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>
    %7 = nvws.aref.create %6 : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]>
    %8 = ttg.local_alloc : () -> !ttg.memdesc<1x256x64xf16, #shared, #smem, mutable>
    %9 = nvws.aref.create %8 : <[!ttg.memdesc<1x256x64xf16, #shared, #smem, mutable>]>
    %10 = ttg.local_alloc : () -> !ttg.memdesc<1x256xf32, #shared1, #smem, mutable>
    %11 = nvws.aref.create %10 : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]>
    %12 = ttg.local_alloc : () -> !ttg.memdesc<1x256xf32, #shared1, #smem, mutable>
    %13 = nvws.aref.create %12 : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]>
    %14:4 = scf.for %arg6 = %c0_i32 to %arg4 step %c64_i32 iter_args(%arg7 = %cst, %arg8 = %cst_1, %arg9 = %token, %arg10 = %token_4) -> (tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>, !ttg.async.token, !ttg.async.token)  : i32 {
      %buffers_9, %token_10 = nvws.aref.put.enter %11 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]> -> !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256>, !ttg.async.token
      ttg.local_store %arg8, %buffers_9 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>> -> !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256>
      nvws.aref.put.exit %11, %token_10 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]>, !ttg.async.token
      %buffers_11, %token_12 = nvws.aref.put.enter %5 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<64x64xf16, #shared, #smem, mutable, 1x64x64>, !ttg.async.token
      nvws.descriptor_load %arg1[%arg6, %c0_i32] 8192 %buffers_11 {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<64x64xf16, #shared>>, i32, i32, !ttg.memdesc<64x64xf16, #shared, #smem, mutable, 1x64x64>
      nvws.aref.put.exit %5, %token_12 [#nvws.async_op<tma_load>] {loop.cluster = 4 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_13, %token_14 = nvws.aref.get.enter %5 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<64x64xf16, #shared, #smem, 1x64x64>, !ttg.async.token
      %16 = ttg.memdesc_trans %buffers_13 {loop.cluster = 2 : i32, loop.stage = 2 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<64x64xf16, #shared, #smem, 1x64x64> -> !ttg.memdesc<64x64xf16, #shared2, #smem, 1x64x64>
      %17 = nvws.aref.buffer %0, %arg9 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64>
      %18 = ttng.tc_gen5_mma %arg0, %16, %17[], %false, %true {loop.cluster = 2 : i32, loop.stage = 2 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<256x64xf16, #shared, #smem>, !ttg.memdesc<64x64xf16, #shared2, #smem, 1x64x64>, !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64>
      nvws.aref.put.exit %0, %arg9 [#nvws.async_op<tc5mma>] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
      nvws.aref.get.exit %5, %token_14 [#nvws.async_op<tc5mma>] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_15, %token_16 = nvws.aref.get.enter %0 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64>, !ttg.async.token
      %19 = nvws.aref.buffer %0, %token_16 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64>
      %result_17, %token_18 = ttng.tmem_load %19[] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64> -> tensor<256x64xf32, #blocked>
      nvws.aref.get.exit %0, %token_16 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
      %20 = "compute_row_max"(%result_17, %arg3) {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : (tensor<256x64xf32, #blocked>, f32) -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %buffers_19, %token_20 = nvws.aref.put.enter %13 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]> -> !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256>, !ttg.async.token
      ttg.local_store %20, %buffers_19 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>> -> !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256>
      nvws.aref.put.exit %13, %token_20 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]>, !ttg.async.token
      %21 = "sub_row_max"(%result_17, %20, %arg3) {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : (tensor<256x64xf32, #blocked>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>, f32) -> tensor<256x64xf32, #blocked>
      %22 = math.exp2 %21 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256x64xf32, #blocked>
      %buffers_21, %token_22 = nvws.aref.get.enter %11 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]> -> !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256>, !ttg.async.token
      %23 = ttg.local_load %buffers_21 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256> -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      nvws.aref.get.exit %11, %token_22 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]>, !ttg.async.token
      %buffers_23, %token_24 = nvws.aref.get.enter %13 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]> -> !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256>, !ttg.async.token
      %24 = ttg.local_load %buffers_23 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : !ttg.memdesc<256xf32, #shared1, #smem, mutable, 1x256> -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      nvws.aref.get.exit %13, %token_24 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256xf32, #shared1, #smem, mutable>]>, !ttg.async.token
      %25 = arith.subf %23, %24 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %26 = arith.subf %arg8, %20 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %27 = math.exp2 %25 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %28 = math.exp2 %26 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %29 = "tt.reduce"(%22) <{axis = 1 : i32}> ({
      ^bb0(%arg11: f32, %arg12: f32):
        %45 = arith.addf %arg11, %arg12 {ttg.partition = array<i32: 0>} : f32
        tt.reduce.return %45 {ttg.partition = array<i32: 0>} : f32
      }) {ttg.partition = array<i32: 0>, ttg.partition.outputs = [array<i32: 0>], loop.cluster = 0 : i32, loop.stage = 4 : i32} : (tensor<256x64xf32, #blocked>) -> tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %30 = arith.mulf %arg7, %28 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %31 = arith.addf %30, %29 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>
      %32 = tt.expand_dims %27 {axis = 1 : i32, loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>> -> tensor<256x1xf32, #blocked>
      %33 = tt.expand_dims %28 {axis = 1 : i32, loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>> -> tensor<256x1xf32, #blocked>
      %34 = tt.broadcast %32 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x1xf32, #blocked> -> tensor<256x64xf32, #blocked>
      %35 = tt.addptr %arg5, %arg6 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 0, 1, 2, 3>} : !tt.ptr<f32>, i32
      %36 = tt.load %35 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 0, 1, 2, 3>} : !tt.ptr<f32>
      %37 = tt.splat %36 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : f32 -> tensor<256x64xf32, #blocked>
      %38 = nvws.aref.buffer %1, %arg10 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
      %result_25, %token_26 = ttng.tmem_load %38[] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64> -> tensor<256x64xf32, #blocked>
      %39 = arith.mulf %result_25, %34 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x64xf32, #blocked>
      %40 = arith.addf %39, %37 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x64xf32, #blocked>
      %buffers_27, %token_28 = nvws.aref.put.enter %7 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<64x64xf16, #shared, #smem, mutable, 1x64x64>, !ttg.async.token
      nvws.descriptor_load %arg2[%arg6, %c0_i32] 8192 %buffers_27 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : !tt.tensordesc<tensor<64x64xf16, #shared>>, i32, i32, !ttg.memdesc<64x64xf16, #shared, #smem, mutable, 1x64x64>
      nvws.aref.put.exit %7, %token_28 [#nvws.async_op<tma_load>] {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_29, %token_30 = nvws.aref.get.enter %7 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<64x64xf16, #shared, #smem, 1x64x64>, !ttg.async.token
      %41 = arith.truncf %22 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256x64xf32, #blocked> to tensor<256x64xf16, #blocked>
      %buffers_31, %token_32 = nvws.aref.put.enter %9 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<256x64xf16, #shared, #smem, mutable, 1x256x64>, !ttg.async.token
      ttg.local_store %41, %buffers_31 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : tensor<256x64xf16, #blocked> -> !ttg.memdesc<256x64xf16, #shared, #smem, mutable, 1x256x64>
      nvws.aref.put.exit %9, %token_32 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 0>} : <[!ttg.memdesc<1x256x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_33, %token_34 = nvws.aref.get.enter %9 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf16, #shared, #smem, mutable>]> -> !ttg.memdesc<256x64xf16, #shared, #smem, 1x256x64>, !ttg.async.token
      %42 = ttng.tmem_store %40, %38[], %true {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : tensor<256x64xf32, #blocked> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
      nvws.aref.put.exit %1, %arg10 [#nvws.async_op<none>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
      %buffers_35, %token_36 = nvws.aref.get.enter %1 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>, !ttg.async.token
      %43 = nvws.aref.buffer %1, %token_36 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
      %44 = ttng.tc_gen5_mma %buffers_33, %buffers_29, %43[], %true, %true {loop.cluster = 0 : i32, loop.stage = 4 : i32, tt.self_latency = 1 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<256x64xf16, #shared, #smem, 1x256x64>, !ttg.memdesc<64x64xf16, #shared, #smem, 1x64x64>, !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
      nvws.aref.get.exit %1, %token_36 [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
      nvws.aref.get.exit %9, %token_34 [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x256x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      nvws.aref.get.exit %7, %token_30 [#nvws.async_op<tc5mma>] {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<1x64x64xf16, #shared, #smem, mutable>]>, !ttg.async.token
      %buffers_37, %token_38 = nvws.aref.put.enter %0 {loop.cluster = 2 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 1>} : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 2x256x64>, !ttg.async.token
      %buffers_39, %token_40 = nvws.aref.put.enter %1 {loop.cluster = 0 : i32, loop.stage = 4 : i32, ttg.partition = array<i32: 3>} : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>, !ttg.async.token
      scf.yield {ttg.partition = array<i32: 0, 1, 2, 3>} %31, %20, %token_38, %token_40 : tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>, !ttg.async.token, !ttg.async.token
    } {tt.scheduled_max_stage = 4 : i32, tt.warp_specialize, ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32, 1 : i32], ttg.warp_specialize.tag = 0 : i32, ttg.partition = array<i32: 0, 1, 2, 3>, ttg.partition.outputs = [array<i32: 0>, array<i32: 0>, array<i32: 1>, array<i32: 3>]}
    ttg.local_dealloc %12 : !ttg.memdesc<1x256xf32, #shared1, #smem, mutable>
    ttg.local_dealloc %10 : !ttg.memdesc<1x256xf32, #shared1, #smem, mutable>
    nvws.aref.put.exit %1, %14#3 [#nvws.async_op<tc5mma>] : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    nvws.aref.put.exit %0, %14#2 [#nvws.async_op<none>] : <[!ttg.memdesc<2x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    %buffers_5, %token_6 = nvws.aref.get.enter %1 : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]> -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>, !ttg.async.token
    %15 = nvws.aref.buffer %1, %token_6 : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token -> !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64>
    %result_7, %token_8 = ttng.tmem_load %15[] : !ttg.memdesc<256x64xf32, #tmem, #ttng.tensor_memory, mutable, 1x256x64> -> tensor<256x64xf32, #blocked>
    nvws.aref.get.exit %1, %token_6 [#nvws.async_op<none>] : <[!ttg.memdesc<1x256x64xf32, #tmem, #ttng.tensor_memory, mutable>]>, !ttg.async.token
    "use"(%14#0, %result_7, %14#1) : (tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>, tensor<256x64xf32, #blocked>, tensor<256xf32, #ttg.slice<{dim = 1, parent = #blocked}>>) -> ()
    tt.return
  }
}
